from openminion.modules.tool import PLUGIN_CONTRACT_VERSION

CONFIG_MGMT_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION
TOOL_CONFIG_ANSIBLE_CHECK = "config.ansible.check"
TOOL_CONFIG_ANSIBLE_FACTS = "config.ansible.facts"
TOOL_CONFIG_SALT_TEST = "config.salt.test"
TOOL_CONFIG_SALT_JOB_STATUS = "config.salt.job_status"

ALL_CONFIG_MGMT_TOOLS = (
    TOOL_CONFIG_ANSIBLE_CHECK,
    TOOL_CONFIG_ANSIBLE_FACTS,
    TOOL_CONFIG_SALT_TEST,
    TOOL_CONFIG_SALT_JOB_STATUS,
)
