"""Lazy export table for the context knowledge package."""

from __future__ import annotations

from typing import Any

PUBLIC_EXPORTS = [
    "CAPABILITY_CITATIONS",
    "CAPABILITY_DURABLE_MEMORY",
    "CAPABILITY_EXPLAIN",
    "CAPABILITY_METHOD_MAP",
    "CAPABILITY_NEIGHBORHOOD",
    "CAPABILITY_PATH",
    "CAPABILITY_PROMOTE_CANDIDATES",
    "CAPABILITY_PROMOTES_TO_DURABLE",
    "CAPABILITY_PROVENANCE",
    "CAPABILITY_QUERY",
    "CAPABILITY_REFRESH",
    "CAPABILITY_WATCH",
    "CAPABILITY_WRITABLE_GRAPH",
    "DEFAULT_REFRESH_MODE",
    "DEFAULT_GRAPHIFY_TIMEOUT_SECONDS",
    "DEFAULT_RETRIEVAL_MAX_CHARS",
    "DEFAULT_RETRIEVAL_MAX_RESULTS",
    "DisabledProviderError",
    "DuplicateProviderError",
    "EVENT_QUERY_COMPLETED",
    "EVENT_QUERY_DEGRADED",
    "EVENT_QUERY_FAILED",
    "EVENT_QUERY_STARTED",
    "EVENT_REFRESH_COMPLETED",
    "EVENT_REFRESH_FAILED",
    "EVENT_REFRESH_STARTED",
    "EVENT_SOURCE_RESOLVED",
    "GraphContextItem",
    "GraphExplainRequest",
    "GraphExplainResult",
    "GraphNeighborhoodRequest",
    "GraphOmittedItem",
    "GraphPathEvidence",
    "GraphPathRequest",
    "GraphPathResult",
    "GraphQueryRequest",
    "GraphQueryResult",
    "GraphRefreshRequest",
    "GraphRefreshResult",
    "GraphSourceRef",
    "GraphViewerLaunchResult",
    "GraphViewerProviderStatus",
    "GraphViewerRequest",
    "GraphViewerSourceError",
    "GraphViewerStatusReport",
    "GraphViewerUnavailableError",
    "HybridDurableMemoryError",
    "InvalidCapabilityError",
    "InvalidLayerError",
    "InvalidProviderTagError",
    "KNOWLEDGE_GRAPH_CAPABILITIES",
    "KNOWLEDGE_GRAPH_CONTRACT_VERSION",
    "KNOWLEDGE_GRAPH_INTERFACE_VERSION",
    "KNOWLEDGE_GRAPH_LAYERS",
    "KNOWLEDGE_GRAPH_PROVIDER_TAGS",
    "KNOWLEDGE_GRAPH_TELEMETRY_EVENTS",
    "KNOWLEDGE_GRAPHS_CONFIG_KEY",
    "KnowledgeGraphCapabilities",
    "KnowledgeGraphError",
    "KnowledgeGraphHealth",
    "KnowledgeGraphLayerConfig",
    "KnowledgeGraphProviderConfig",
    "KnowledgeGraphProviderFactory",
    "KnowledgeGraphRefreshConfig",
    "KnowledgeGraphRegistry",
    "KnowledgeGraphRetrievalConfig",
    "KnowledgeGraphSource",
    "KnowledgeGraphService",
    "KnowledgeGraphsConfig",
    "LAYER_SECOND_BRAIN",
    "LAYER_THIRD_BRAIN",
    "MissingRequiredCapabilityError",
    "MultiActiveSecondBrainError",
    "OpenMinionMemoryGraphFakosProvider",
    "ResolvedKnowledgeGraphProvider",
    "PROVIDER_GRAPHIFY",
    "PROVIDER_PRAGMAGRAPH",
    "build_knowledge_graph_service",
    "empty_knowledge_graph_service",
    "inspect_graph_viewer_status",
    "knowledge_graphs_config_from_mapping",
    "launch_graph_viewer",
    "report_optional_capabilities",
    "resolve_knowledge_graphs_config",
    "TAG_ARTIFACT_GRAPH",
    "TAG_CODE_GRAPH",
    "TAG_DOCUMENT_GRAPH",
    "TAG_HOSTED_GRAPH",
    "TAG_HYBRID_GRAPH",
    "UnknownProviderError",
    "UnsupportedCapabilityError",
    "validate_provider_capabilities",
]

LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "CAPABILITY_CITATIONS": (".constants", "CAPABILITY_CITATIONS"),
    "CAPABILITY_DURABLE_MEMORY": (".constants", "CAPABILITY_DURABLE_MEMORY"),
    "CAPABILITY_EXPLAIN": (".constants", "CAPABILITY_EXPLAIN"),
    "CAPABILITY_METHOD_MAP": (".interfaces", "CAPABILITY_METHOD_MAP"),
    "CAPABILITY_NEIGHBORHOOD": (".constants", "CAPABILITY_NEIGHBORHOOD"),
    "CAPABILITY_PATH": (".constants", "CAPABILITY_PATH"),
    "CAPABILITY_PROMOTE_CANDIDATES": (".constants", "CAPABILITY_PROMOTE_CANDIDATES"),
    "CAPABILITY_PROMOTES_TO_DURABLE": (".constants", "CAPABILITY_PROMOTES_TO_DURABLE"),
    "CAPABILITY_PROVENANCE": (".constants", "CAPABILITY_PROVENANCE"),
    "CAPABILITY_QUERY": (".constants", "CAPABILITY_QUERY"),
    "CAPABILITY_REFRESH": (".constants", "CAPABILITY_REFRESH"),
    "CAPABILITY_WATCH": (".constants", "CAPABILITY_WATCH"),
    "CAPABILITY_WRITABLE_GRAPH": (".constants", "CAPABILITY_WRITABLE_GRAPH"),
    "DEFAULT_REFRESH_MODE": (".config", "DEFAULT_REFRESH_MODE"),
    "DEFAULT_GRAPHIFY_TIMEOUT_SECONDS": (".config", "DEFAULT_GRAPHIFY_TIMEOUT_SECONDS"),
    "DEFAULT_RETRIEVAL_MAX_CHARS": (".config", "DEFAULT_RETRIEVAL_MAX_CHARS"),
    "DEFAULT_RETRIEVAL_MAX_RESULTS": (".config", "DEFAULT_RETRIEVAL_MAX_RESULTS"),
    "DisabledProviderError": (".errors", "DisabledProviderError"),
    "DuplicateProviderError": (".errors", "DuplicateProviderError"),
    "EVENT_QUERY_COMPLETED": (".constants", "EVENT_QUERY_COMPLETED"),
    "EVENT_QUERY_DEGRADED": (".constants", "EVENT_QUERY_DEGRADED"),
    "EVENT_QUERY_FAILED": (".constants", "EVENT_QUERY_FAILED"),
    "EVENT_QUERY_STARTED": (".constants", "EVENT_QUERY_STARTED"),
    "EVENT_REFRESH_COMPLETED": (".constants", "EVENT_REFRESH_COMPLETED"),
    "EVENT_REFRESH_FAILED": (".constants", "EVENT_REFRESH_FAILED"),
    "EVENT_REFRESH_STARTED": (".constants", "EVENT_REFRESH_STARTED"),
    "EVENT_SOURCE_RESOLVED": (".constants", "EVENT_SOURCE_RESOLVED"),
    "GraphContextItem": (".models", "GraphContextItem"),
    "GraphExplainRequest": (".models", "GraphExplainRequest"),
    "GraphExplainResult": (".models", "GraphExplainResult"),
    "GraphNeighborhoodRequest": (".models", "GraphNeighborhoodRequest"),
    "GraphOmittedItem": (".models", "GraphOmittedItem"),
    "GraphPathEvidence": (".models", "GraphPathEvidence"),
    "GraphPathRequest": (".models", "GraphPathRequest"),
    "GraphPathResult": (".models", "GraphPathResult"),
    "GraphQueryRequest": (".models", "GraphQueryRequest"),
    "GraphQueryResult": (".models", "GraphQueryResult"),
    "GraphRefreshRequest": (".models", "GraphRefreshRequest"),
    "GraphRefreshResult": (".models", "GraphRefreshResult"),
    "GraphSourceRef": (".models", "GraphSourceRef"),
    "GraphViewerLaunchResult": (".viewer_models", "GraphViewerLaunchResult"),
    "GraphViewerProviderStatus": (".viewer_models", "GraphViewerProviderStatus"),
    "GraphViewerRequest": (".viewer_models", "GraphViewerRequest"),
    "GraphViewerSourceError": (".errors", "GraphViewerSourceError"),
    "GraphViewerStatusReport": (".viewer_models", "GraphViewerStatusReport"),
    "GraphViewerUnavailableError": (".errors", "GraphViewerUnavailableError"),
    "HybridDurableMemoryError": (".errors", "HybridDurableMemoryError"),
    "InvalidCapabilityError": (".errors", "InvalidCapabilityError"),
    "InvalidLayerError": (".errors", "InvalidLayerError"),
    "InvalidProviderTagError": (".errors", "InvalidProviderTagError"),
    "KNOWLEDGE_GRAPH_CAPABILITIES": (".constants", "KNOWLEDGE_GRAPH_CAPABILITIES"),
    "KNOWLEDGE_GRAPH_CONTRACT_VERSION": (
        ".contracts",
        "KNOWLEDGE_GRAPH_CONTRACT_VERSION",
    ),
    "KNOWLEDGE_GRAPH_INTERFACE_VERSION": (
        ".interfaces",
        "KNOWLEDGE_GRAPH_INTERFACE_VERSION",
    ),
    "KNOWLEDGE_GRAPH_LAYERS": (".constants", "KNOWLEDGE_GRAPH_LAYERS"),
    "KNOWLEDGE_GRAPH_PROVIDER_TAGS": (".constants", "KNOWLEDGE_GRAPH_PROVIDER_TAGS"),
    "KNOWLEDGE_GRAPH_TELEMETRY_EVENTS": (
        ".constants",
        "KNOWLEDGE_GRAPH_TELEMETRY_EVENTS",
    ),
    "KNOWLEDGE_GRAPHS_CONFIG_KEY": (".constants", "KNOWLEDGE_GRAPHS_CONFIG_KEY"),
    "KnowledgeGraphCapabilities": (".models", "KnowledgeGraphCapabilities"),
    "KnowledgeGraphError": (".errors", "KnowledgeGraphError"),
    "KnowledgeGraphHealth": (".models", "KnowledgeGraphHealth"),
    "KnowledgeGraphLayerConfig": (".config", "KnowledgeGraphLayerConfig"),
    "KnowledgeGraphProviderConfig": (".config", "KnowledgeGraphProviderConfig"),
    "KnowledgeGraphProviderFactory": (".registry", "KnowledgeGraphProviderFactory"),
    "KnowledgeGraphRefreshConfig": (".config", "KnowledgeGraphRefreshConfig"),
    "KnowledgeGraphRegistry": (".registry", "KnowledgeGraphRegistry"),
    "KnowledgeGraphRetrievalConfig": (".config", "KnowledgeGraphRetrievalConfig"),
    "KnowledgeGraphSource": (".interfaces", "KnowledgeGraphSource"),
    "KnowledgeGraphService": (".service", "KnowledgeGraphService"),
    "KnowledgeGraphsConfig": (".config", "KnowledgeGraphsConfig"),
    "LAYER_SECOND_BRAIN": (".constants", "LAYER_SECOND_BRAIN"),
    "LAYER_THIRD_BRAIN": (".constants", "LAYER_THIRD_BRAIN"),
    "MissingRequiredCapabilityError": (".errors", "MissingRequiredCapabilityError"),
    "MultiActiveSecondBrainError": (".errors", "MultiActiveSecondBrainError"),
    "OpenMinionMemoryGraphFakosProvider": (
        ".viewer",
        "OpenMinionMemoryGraphFakosProvider",
    ),
    "ResolvedKnowledgeGraphProvider": (".registry", "ResolvedKnowledgeGraphProvider"),
    "PROVIDER_GRAPHIFY": (".constants", "PROVIDER_GRAPHIFY"),
    "PROVIDER_PRAGMAGRAPH": (".constants", "PROVIDER_PRAGMAGRAPH"),
    "build_knowledge_graph_service": (".service", "build_knowledge_graph_service"),
    "empty_knowledge_graph_service": (".service", "empty_knowledge_graph_service"),
    "inspect_graph_viewer_status": (".viewer", "inspect_graph_viewer_status"),
    "knowledge_graphs_config_from_mapping": (
        ".config",
        "knowledge_graphs_config_from_mapping",
    ),
    "launch_graph_viewer": (".viewer", "launch_graph_viewer"),
    "report_optional_capabilities": (".registry", "report_optional_capabilities"),
    "resolve_knowledge_graphs_config": (".config", "resolve_knowledge_graphs_config"),
    "TAG_ARTIFACT_GRAPH": (".constants", "TAG_ARTIFACT_GRAPH"),
    "TAG_CODE_GRAPH": (".constants", "TAG_CODE_GRAPH"),
    "TAG_DOCUMENT_GRAPH": (".constants", "TAG_DOCUMENT_GRAPH"),
    "TAG_HOSTED_GRAPH": (".constants", "TAG_HOSTED_GRAPH"),
    "TAG_HYBRID_GRAPH": (".constants", "TAG_HYBRID_GRAPH"),
    "UnknownProviderError": (".errors", "UnknownProviderError"),
    "UnsupportedCapabilityError": (".errors", "UnsupportedCapabilityError"),
    "validate_provider_capabilities": (".registry", "validate_provider_capabilities"),
}


def resolve_lazy_export(*, package_name: str, name: str) -> Any:
    target = LAZY_EXPORTS.get(name)
    if not target:
        raise AttributeError(name)
    module_name, attr_name = target
    module = __import__(package_name + module_name, fromlist=[attr_name])
    return getattr(module, attr_name)
