from openminion.modules.controlplane.constants import (
    CALLER_HANDLES_DELIVERY_METADATA_KEY,
)

OPENMINION_MEMORY_CAPSULE_STRATEGY_ENV = "OPENMINION_MEMORY_CAPSULE_STRATEGY"
OPENMINION_MEMORY_DYNAMIC_RETRIEVAL_ENABLED_ENV = (
    "OPENMINION_MEMORY_DYNAMIC_RETRIEVAL_ENABLED"
)

__all__ = [
    "CALLER_HANDLES_DELIVERY_METADATA_KEY",
    "OPENMINION_MEMORY_CAPSULE_STRATEGY_ENV",
    "OPENMINION_MEMORY_DYNAMIC_RETRIEVAL_ENABLED_ENV",
]
