"""Public tool identifiers for graph access."""

from openminion.modules.tool.contracts.model_ids import (
    MODEL_GRAPH_NEIGHBORHOOD,
    MODEL_GRAPH_QUERY,
    MODEL_GRAPH_REFRESH,
)

TOOL_GRAPH_QUERY = MODEL_GRAPH_QUERY
TOOL_GRAPH_NEIGHBORHOOD = MODEL_GRAPH_NEIGHBORHOOD
TOOL_GRAPH_REFRESH = MODEL_GRAPH_REFRESH

ALL_GRAPH_TOOLS = (
    TOOL_GRAPH_QUERY,
    TOOL_GRAPH_NEIGHBORHOOD,
    TOOL_GRAPH_REFRESH,
)

__all__ = [
    "ALL_GRAPH_TOOLS",
    "TOOL_GRAPH_NEIGHBORHOOD",
    "TOOL_GRAPH_QUERY",
    "TOOL_GRAPH_REFRESH",
]
