FETCH_TINYFISH_PROVIDER_ID = "tinyfish"
TINYFISH_FETCH_API_URL_ENV = "TINYFISH_FETCH_API_URL"
TINYFISH_FETCH_TIMEOUT_SECONDS_ENV = "TINYFISH_FETCH_TIMEOUT_SECONDS"
DEFAULT_TINYFISH_FETCH_API_URL = "https://api.fetch.tinyfish.ai"
DEFAULT_TINYFISH_FETCH_TIMEOUT_SECONDS = 150.0

__all__ = [
    "DEFAULT_TINYFISH_FETCH_API_URL",
    "DEFAULT_TINYFISH_FETCH_TIMEOUT_SECONDS",
    "FETCH_TINYFISH_PROVIDER_ID",
    "TINYFISH_FETCH_API_URL_ENV",
    "TINYFISH_FETCH_TIMEOUT_SECONDS_ENV",
]
