"""Operator-tunable defaults for modules tool authoring."""

TOOL_AUTHORING_ALLOWED_DEPS_ENV = "OPENMINION_AUTHORED_TOOL_ALLOWED_DEPS"
TOOL_AUTHORING_TEST_TIMEOUT_S = 30.0
TOOL_AUTHORING_TEST_MAX_OUTPUT_BYTES = 1_048_576
TOOL_AUTHORING_TEST_ADDRESS_SPACE_BYTES = 512 * 1024 * 1024
TOOL_AUTHORING_TEST_CPU_SECONDS = 30.0
TOOL_AUTHORING_MIN_SUCCESS_COUNT = 20
TOOL_AUTHORING_MAX_FAILURE_RATE = 0.05
TOOL_AUTHORING_REQUIRED_TEST_PASS_RATE = 1.0

__all__ = [
    "TOOL_AUTHORING_ALLOWED_DEPS_ENV",
    "TOOL_AUTHORING_MAX_FAILURE_RATE",
    "TOOL_AUTHORING_MIN_SUCCESS_COUNT",
    "TOOL_AUTHORING_REQUIRED_TEST_PASS_RATE",
    "TOOL_AUTHORING_TEST_ADDRESS_SPACE_BYTES",
    "TOOL_AUTHORING_TEST_CPU_SECONDS",
    "TOOL_AUTHORING_TEST_MAX_OUTPUT_BYTES",
    "TOOL_AUTHORING_TEST_TIMEOUT_S",
]
