"""Fixed values for modules tool authoring."""

TOOL_AUTHORING_STATUS_DRAFTED = "drafted"
TOOL_AUTHORING_STATUS_INSPECTED = "inspected"
TOOL_AUTHORING_STATUS_REGISTERED = "registered"
TOOL_AUTHORING_STATUS_ABANDONED = "abandoned"

TOOL_AUTHORING_TIER_EXPERIMENTAL = "experimental"
TOOL_AUTHORING_TIER_TRUSTED = "trusted"

TOOL_AUTHORING_SCOPE_POWER_USER = "POWER_USER"

TOOL_AUTHORING_EVENT_DRAFTED = "tool_authoring.drafted"
TOOL_AUTHORING_EVENT_INSPECTED = "tool_authoring.inspected"
TOOL_AUTHORING_EVENT_REGISTERED = "tool_authoring.registered"
TOOL_AUTHORING_EVENT_INVOKED = "tool_authoring.invoked"
TOOL_AUTHORING_EVENT_PROMOTED = "tool_authoring.promoted"
TOOL_AUTHORING_EVENT_FORCE_PROMOTED = "tool_authoring.force_promoted"
TOOL_AUTHORING_EVENT_SCOPE_CHANGED = "tool_authoring.scope_changed"
TOOL_AUTHORING_EVENT_REMOVED = "tool_authoring.removed"
TOOL_AUTHORING_EVENT_POLICY_GRANT_ISSUED = "policy.grant_issued"
TOOL_AUTHORING_EVENT_POLICY_GRANT_REVOKED = "policy.grant_revoked"

TOOL_AUTHORING_TARGET_DRAFT = "draft"
TOOL_AUTHORING_TARGET_TOOL = "tool"

AUTHORED_TOOL_ERROR_FAILED = "AUTHORED_TOOL_FAILED"
AUTHORED_TOOL_ERROR_NOT_FOUND = "AUTHORED_TOOL_NOT_FOUND"
AUTHORED_TOOL_ERROR_REMOVED = "AUTHORED_TOOL_REMOVED"
AUTHORED_TOOL_ERROR_LIMIT = "AUTHORED_TOOL_LIMIT_EXCEEDED"
AUTHORED_TOOL_ERROR_COLLECTION = "TEST_COLLECTION_FAILED"

TOOL_AUTHORING_REGISTER_REASON = "auto_register"

__all__ = [
    "AUTHORED_TOOL_ERROR_COLLECTION",
    "AUTHORED_TOOL_ERROR_FAILED",
    "AUTHORED_TOOL_ERROR_LIMIT",
    "AUTHORED_TOOL_ERROR_NOT_FOUND",
    "AUTHORED_TOOL_ERROR_REMOVED",
    "TOOL_AUTHORING_EVENT_DRAFTED",
    "TOOL_AUTHORING_EVENT_FORCE_PROMOTED",
    "TOOL_AUTHORING_EVENT_INSPECTED",
    "TOOL_AUTHORING_EVENT_INVOKED",
    "TOOL_AUTHORING_EVENT_POLICY_GRANT_ISSUED",
    "TOOL_AUTHORING_EVENT_POLICY_GRANT_REVOKED",
    "TOOL_AUTHORING_EVENT_PROMOTED",
    "TOOL_AUTHORING_EVENT_REGISTERED",
    "TOOL_AUTHORING_EVENT_REMOVED",
    "TOOL_AUTHORING_EVENT_SCOPE_CHANGED",
    "TOOL_AUTHORING_REGISTER_REASON",
    "TOOL_AUTHORING_SCOPE_POWER_USER",
    "TOOL_AUTHORING_STATUS_ABANDONED",
    "TOOL_AUTHORING_STATUS_DRAFTED",
    "TOOL_AUTHORING_STATUS_INSPECTED",
    "TOOL_AUTHORING_STATUS_REGISTERED",
    "TOOL_AUTHORING_TARGET_DRAFT",
    "TOOL_AUTHORING_TARGET_TOOL",
    "TOOL_AUTHORING_TIER_EXPERIMENTAL",
    "TOOL_AUTHORING_TIER_TRUSTED",
]
