from pathlib import Path

from openminion.modules.paths import IDENTITY_DB_FILENAME, IDENTITY_DIRNAME

DEFAULT_CONFIG_FILENAME = "identity.yaml"
DEFAULT_IDENTITY_DB_FILENAME = IDENTITY_DB_FILENAME
DEFAULT_IDENTITY_CTL_DB_FILENAME = "identityctl.db"
DEFAULT_INTEGRATED_STORAGE_SUBPATH = (
    Path(IDENTITY_DIRNAME) / DEFAULT_IDENTITY_CTL_DB_FILENAME
)
DEFAULT_INTEGRATED_BUNDLE_SUBPATH = Path(IDENTITY_DIRNAME)
DEFAULT_PROFILES_SUBPATH = Path("profiles")
