from pathlib import Path

from openminion.modules.paths import IDENTITY_DB_FILENAME, IDENTITY_DIRNAME

DEFAULT_CONFIG_FILENAME = "identity.yaml"
DEFAULT_IDENTITY_DB_FILENAME = IDENTITY_DB_FILENAME
DEFAULT_IDENTITY_CTL_DB_FILENAME = "identityctl.db"
DEFAULT_INTEGRATED_STORAGE_SUBPATH = (
    Path(IDENTITY_DIRNAME) / DEFAULT_IDENTITY_CTL_DB_FILENAME
)
DEFAULT_INTEGRATED_BUNDLE_SUBPATH = Path(IDENTITY_DIRNAME)
DEFAULT_PROFILES_SUBPATH = Path("profiles")

IDENTITY_RUNTIME_STATUS_NOT_STARTED = "not_started"
IDENTITY_RUNTIME_STATUS_IDENTITYCTL_UNAVAILABLE = "identityctl_unavailable"
IDENTITY_RUNTIME_STATUS_IDENTITY_ROOT_MISSING = "identity_root_missing"
IDENTITY_RUNTIME_STATUS_IDENTITY_ROOT_NOT_DIRECTORY = "identity_root_not_directory"
IDENTITY_RUNTIME_STATUS_NO_YAML_PROFILES = "no_yaml_profiles"
IDENTITY_RUNTIME_STATUS_PARTIAL_FAILURE = "partial_failure"
IDENTITY_RUNTIME_STATUS_SYNC_FAILED = "sync_failed"
IDENTITY_RUNTIME_STATUS_SYNCED = "synced"
IDENTITY_RUNTIME_STATUS_BUNDLE_ROOT_UNSET = "bundle_root_unset"
IDENTITY_RUNTIME_STATUS_BUNDLE_INVALID = "bundle_invalid"
IDENTITY_RUNTIME_STATUS_SKIPPED_AUTHORITY = "skipped_authority"
IDENTITY_RUNTIME_STATUS_SKIPPED_UNCHANGED = "skipped_unchanged"
IDENTITY_RUNTIME_STATUS_BUNDLE_EMPTY = "bundle_empty"
IDENTITY_RUNTIME_STATUS_IMPORTED = "imported"
IDENTITY_RUNTIME_STATUS_IMPORT_FAILED = "import_failed"
