from openminion.modules.tool import PLUGIN_CONTRACT_VERSION

CLOUD_OPS_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION
TOOL_CLOUD_SSM_INVENTORY = "cloud.ssm.inventory"
TOOL_CLOUD_SSM_COMMAND_STATUS = "cloud.ssm.command_status"

ALL_CLOUD_OPS_TOOLS = (
    TOOL_CLOUD_SSM_INVENTORY,
    TOOL_CLOUD_SSM_COMMAND_STATUS,
)
