from openminion.modules.tool import PLUGIN_CONTRACT_VERSION

K8S_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION
TOOL_K8S_WORKLOAD_GET = "k8s.workload.get"
TOOL_K8S_WORKLOAD_LIST = "k8s.workload.list"
TOOL_K8S_EVENTS_LIST = "k8s.events.list"
TOOL_K8S_LOGS_GET = "k8s.logs.get"
TOOL_K8S_ROLLOUT_STATUS = "k8s.rollout.status"

ALL_K8S_TOOLS = (
    TOOL_K8S_WORKLOAD_GET,
    TOOL_K8S_WORKLOAD_LIST,
    TOOL_K8S_EVENTS_LIST,
    TOOL_K8S_LOGS_GET,
    TOOL_K8S_ROLLOUT_STATUS,
)
