OPENMINION_BRAIN_MODEL_ENV = "OPENMINION_BRAIN_MODEL"
OPENMINION_BRAIN_DECIDE_MODEL_ENV = "OPENMINION_BRAIN_DECIDE_MODEL"
OPENMINION_BRAIN_PLAN_MODEL_ENV = "OPENMINION_BRAIN_PLAN_MODEL"
OPENMINION_BRAIN_REFLECT_MODEL_ENV = "OPENMINION_BRAIN_REFLECT_MODEL"
OPENMINION_BRAIN_SUMMARIZE_MODEL_ENV = "OPENMINION_BRAIN_SUMMARIZE_MODEL"
OPENMINION_BRAIN_MAX_TICKS_ENV = "OPENMINION_BRAIN_MAX_TICKS"
OPENMINION_BRAIN_MAX_TOOL_CALLS_ENV = "OPENMINION_BRAIN_MAX_TOOL_CALLS"
OPENMINION_BRAIN_MAX_A2A_CALLS_ENV = "OPENMINION_BRAIN_MAX_A2A_CALLS"
OPENMINION_BRAIN_MAX_TOTAL_LLM_TOKENS_ENV = "OPENMINION_BRAIN_MAX_TOTAL_LLM_TOKENS"
OPENMINION_BRAIN_MAX_ELAPSED_MS_ENV = "OPENMINION_BRAIN_MAX_ELAPSED_MS"
OPENMINION_BRAIN_REFLECTION_ENABLED_ENV = "OPENMINION_BRAIN_REFLECTION_ENABLED"

__all__ = [
    "OPENMINION_BRAIN_MODEL_ENV",
    "OPENMINION_BRAIN_DECIDE_MODEL_ENV",
    "OPENMINION_BRAIN_PLAN_MODEL_ENV",
    "OPENMINION_BRAIN_REFLECT_MODEL_ENV",
    "OPENMINION_BRAIN_SUMMARIZE_MODEL_ENV",
    "OPENMINION_BRAIN_MAX_TICKS_ENV",
    "OPENMINION_BRAIN_MAX_TOOL_CALLS_ENV",
    "OPENMINION_BRAIN_MAX_A2A_CALLS_ENV",
    "OPENMINION_BRAIN_MAX_TOTAL_LLM_TOKENS_ENV",
    "OPENMINION_BRAIN_MAX_ELAPSED_MS_ENV",
    "OPENMINION_BRAIN_REFLECTION_ENABLED_ENV",
]
