"""Shared OpenMinion constants."""

from __future__ import annotations

OPENMINION_HOME_ENV = "OPENMINION_HOME"
OPENMINION_DATA_ROOT_ENV = "OPENMINION_DATA_ROOT"
OPENMINION_GENERATED_ROOT_ENV = "OPENMINION_GENERATED_ROOT"
OPENMINION_CONFIG_ROOT_ENV = "OPENMINION_CONFIG_ROOT"
OPENMINION_CONFIG_PATH_ENV = "OPENMINION_CONFIG_PATH"
OPENMINION_DATA_ROOT_ENFORCEMENT_ENV = "OPENMINION_DATA_ROOT_ENFORCEMENT"
OPENMINION_MODULE_STANDALONE_ENV = "OPENMINION_MODULE_STANDALONE"
OPENMINION_LOG_LEVEL_ENV = "OPENMINION_LOG_LEVEL"
OPENMINION_COLOR_ENV = "OPENMINION_COLOR"
OPENMINION_LOG_COLOR_ENV = "OPENMINION_LOG_COLOR"
NO_COLOR_ENV = "NO_COLOR"
OPENMINION_IDENTITY_ROOT_ENV = "OPENMINION_IDENTITY_ROOT"
OPENMINION_IDENTITY_DB_ENV = "OPENMINION_IDENTITY_DB"
OPENMINION_TURN_TIMEOUT_SECONDS_ENV = "OPENMINION_TURN_TIMEOUT_SECONDS"
OPENMINION_TRACE_REQUESTS_ENV = "OPENMINION_TRACE_REQUESTS"
OPENMINION_TRACE_REQUESTS_DIR_ENV = "OPENMINION_TRACE_REQUESTS_DIR"
OPENMINION_LLM_DEBUG_ENV = "OPENMINION_LLM_DEBUG"
OPENMINION_LLM_DEBUG_PROVIDER_ENV = "OPENMINION_LLM_DEBUG_PROVIDER"
OPENMINION_LLM_DEBUG_DIR_ENV = "OPENMINION_LLM_DEBUG_DIR"
OPENMINION_LLM_DEBUG_MAX_CHARS_ENV = "OPENMINION_LLM_DEBUG_MAX_CHARS"
OPENMINION_STRICT_PROVIDER_RESPONSE_CONTRACTS_ENV = (
    "OPENMINION_STRICT_PROVIDER_RESPONSE_CONTRACTS"
)
OPENMINION_PROVIDER_INTERFACE_STRICT_ENV = "OPENMINION_PROVIDER_INTERFACE_STRICT"
OPENMINION_DISABLE_LLMCTL_BRIDGE_ENV = "OPENMINION_DISABLE_LLMCTL_BRIDGE"
OPENMINION_DAEMON_AUTO_START_ENV = "OPENMINION_DAEMON_AUTO_START"
OPENMINION_STORAGE_BACKEND_ENV = "OPENMINION_STORAGE_BACKEND"
OPENMINION_STORAGE_POSTGRES_URL_ENV = "OPENMINION_STORAGE_POSTGRES_URL"
OPENMINION_STORAGE_POSTGRES_POOL_MIN_ENV = "OPENMINION_STORAGE_POSTGRES_POOL_MIN"
OPENMINION_STORAGE_POSTGRES_POOL_MAX_ENV = "OPENMINION_STORAGE_POSTGRES_POOL_MAX"

BASE_DEFAULT_CONFIG_DIRNAME = ".openminion"
BASE_DEFAULT_CONFIG_FILENAME = "agents.json"
BASE_STATE_DIRNAME = "state"
BASE_STATE_DB_FILENAME = "openminion.db"

BASE_BOOL_TRUE_VALUES = frozenset({"1", "true", "yes", "on"})
BASE_BOOL_FALSE_VALUES = frozenset({"0", "false", "no", "off"})
BASE_COLOR_FORCE_TRUE_VALUES = frozenset((*BASE_BOOL_TRUE_VALUES, "always"))
BASE_COLOR_FORCE_FALSE_VALUES = BASE_BOOL_FALSE_VALUES

STATE_KEY_FINALIZATION_STATUS = "finalization_status"
STATE_KEY_WORKING = "working_state"
STATE_KEY_ACTIVE = "active_state"
STATE_KEY_SOURCE_OUTCOME = "source_outcome_status"

__all__ = [
    "BASE_BOOL_FALSE_VALUES",
    "BASE_BOOL_TRUE_VALUES",
    "BASE_COLOR_FORCE_FALSE_VALUES",
    "BASE_COLOR_FORCE_TRUE_VALUES",
    "BASE_DEFAULT_CONFIG_DIRNAME",
    "BASE_DEFAULT_CONFIG_FILENAME",
    "BASE_STATE_DB_FILENAME",
    "BASE_STATE_DIRNAME",
    "NO_COLOR_ENV",
    "OPENMINION_COLOR_ENV",
    "OPENMINION_CONFIG_PATH_ENV",
    "OPENMINION_CONFIG_ROOT_ENV",
    "OPENMINION_DATA_ROOT_ENFORCEMENT_ENV",
    "OPENMINION_DATA_ROOT_ENV",
    "OPENMINION_GENERATED_ROOT_ENV",
    "OPENMINION_HOME_ENV",
    "OPENMINION_IDENTITY_DB_ENV",
    "OPENMINION_IDENTITY_ROOT_ENV",
    "OPENMINION_LOG_COLOR_ENV",
    "OPENMINION_LOG_LEVEL_ENV",
    "OPENMINION_MODULE_STANDALONE_ENV",
    "OPENMINION_TURN_TIMEOUT_SECONDS_ENV",
    "OPENMINION_TRACE_REQUESTS_ENV",
    "OPENMINION_TRACE_REQUESTS_DIR_ENV",
    "OPENMINION_LLM_DEBUG_ENV",
    "OPENMINION_LLM_DEBUG_PROVIDER_ENV",
    "OPENMINION_LLM_DEBUG_DIR_ENV",
    "OPENMINION_LLM_DEBUG_MAX_CHARS_ENV",
    "OPENMINION_PROVIDER_INTERFACE_STRICT_ENV",
    "OPENMINION_STRICT_PROVIDER_RESPONSE_CONTRACTS_ENV",
    "OPENMINION_DISABLE_LLMCTL_BRIDGE_ENV",
    "OPENMINION_STORAGE_BACKEND_ENV",
    "OPENMINION_STORAGE_POSTGRES_URL_ENV",
    "OPENMINION_STORAGE_POSTGRES_POOL_MIN_ENV",
    "OPENMINION_STORAGE_POSTGRES_POOL_MAX_ENV",
    "STATE_KEY_ACTIVE",
    "STATE_KEY_FINALIZATION_STATUS",
    "STATE_KEY_SOURCE_OUTCOME",
    "STATE_KEY_WORKING",
]
