"""Canonical package identity for the public openminion distribution."""

OPENMINION_PACKAGE_NAME = "openminion"
OPENMINION_VERSION = "0.0.2"
OPENMINION_INITIAL_PUBLIC_VERSION = "0.0.1"
OPENMINION_REASONING_VERSION = "0.2.0"
OPENMINION_SCAFFOLD_DEFAULT_VERSION = "0.0.1"

__all__ = [
    "OPENMINION_INITIAL_PUBLIC_VERSION",
    "OPENMINION_PACKAGE_NAME",
    "OPENMINION_REASONING_VERSION",
    "OPENMINION_SCAFFOLD_DEFAULT_VERSION",
    "OPENMINION_VERSION",
]
