TOOL_OBSERVABILITY_PROM_RULES = "observability.prometheus.rules"
TOOL_OBSERVABILITY_PROM_ALERTS = "observability.prometheus.alerts"
TOOL_OBSERVABILITY_PROM_QUERY = "observability.prometheus.query"
TOOL_OBSERVABILITY_TRACE_LOOKUP = "observability.otel.trace"

ALL_OBSERVABILITY_TOOLS = (
    TOOL_OBSERVABILITY_PROM_RULES,
    TOOL_OBSERVABILITY_PROM_ALERTS,
    TOOL_OBSERVABILITY_PROM_QUERY,
    TOOL_OBSERVABILITY_TRACE_LOOKUP,
)
