SERPAPI_SEARCH_PROVIDER_ID = "serpapi"
SERPAPI_GOOGLE_ENGINE = "google"
SERPAPI_API_URL_ENV = "SERPAPI_API_URL"
SERPAPI_TIMEOUT_SECONDS_ENV = "SERPAPI_TIMEOUT_SECONDS"
DEFAULT_SERPAPI_API_URL = "https://serpapi.com/search"
DEFAULT_SERPAPI_TIMEOUT_SECONDS = 20.0

__all__ = [
    "DEFAULT_SERPAPI_API_URL",
    "DEFAULT_SERPAPI_TIMEOUT_SECONDS",
    "SERPAPI_API_URL_ENV",
    "SERPAPI_GOOGLE_ENGINE",
    "SERPAPI_SEARCH_PROVIDER_ID",
    "SERPAPI_TIMEOUT_SECONDS_ENV",
]
