from pathlib import Path

DEFAULT_SQLITE_FILENAME = "telemetry.db"
DEFAULT_STANDALONE_ROOT_SUBPATH = Path(".openminion") / "telemetry"
DEFAULT_STANDALONE_SQLITE_SUBPATH = (
    DEFAULT_STANDALONE_ROOT_SUBPATH / DEFAULT_SQLITE_FILENAME
)
DEFAULT_INTEGRATED_SQLITE_SUBPATH = Path("telemetry") / DEFAULT_SQLITE_FILENAME

RUNTIME_MODE_HOT = "hot"
TRACE_HOME_ROOT_METADATA_KEY = "__trace_home_root"
