TOOL_SELECTION_MODE_AUTO = "auto"
TOOL_SELECTION_MODE_MANUAL = "manual"
TOOL_SELECTION_MODE_FORCED = "forced"

DEFAULT_MAX_TOOLS = 5
DEFAULT_MIN_CONFIDENCE = 0.5

CATEGORY_WEB = "web"
CATEGORY_FILE = "file"
CATEGORY_EXEC = "exec"
CATEGORY_BROWSER = "browser"
