from openminion.modules.tool import PLUGIN_CONTRACT_VERSION

MEMORY_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION
CONTRACT_VERSION = MEMORY_PLUGIN_INTERFACE_VERSION

__all__ = [
    "CONTRACT_VERSION",
    "MEMORY_PLUGIN_INTERFACE_VERSION",
]
