BRAVE_SEARCH_PROVIDER_ID = "brave"
BRAVE_SEARCH_API_ENDPOINT = "https://api.search.brave.com/res/v1/web/search"
BRAVE_SEARCH_DEFAULT_TIMEOUT_SECONDS = 20.0
BRAVE_SEARCH_DEFAULT_COUNT = 10
BRAVE_SEARCH_MAX_COUNT = 20
BRAVE_SEARCH_MAX_OFFSET = 9

__all__ = [
    "BRAVE_SEARCH_API_ENDPOINT",
    "BRAVE_SEARCH_DEFAULT_COUNT",
    "BRAVE_SEARCH_DEFAULT_TIMEOUT_SECONDS",
    "BRAVE_SEARCH_MAX_COUNT",
    "BRAVE_SEARCH_MAX_OFFSET",
    "BRAVE_SEARCH_PROVIDER_ID",
]
