from pathlib import Path

DEFAULT_SCHEMA_HEAD = "v1"
DEFAULT_STANDALONE_ROOT_SUBPATH = Path(".openminion") / "storage"
DEFAULT_STANDALONE_SQLITE_SUBPATH = DEFAULT_STANDALONE_ROOT_SUBPATH / "storage.db"
DEFAULT_INTEGRATED_ROOT_SUBPATH = Path("storage")
DEFAULT_INTEGRATED_SQLITE_SUBPATH = DEFAULT_INTEGRATED_ROOT_SUBPATH / "storage.db"
