TOOL_GITOPS_APP_STATUS = "gitops.app.status"
TOOL_GITOPS_APP_DIFF = "gitops.app.diff"
TOOL_GITOPS_SOURCE_REVISION = "gitops.source.revision"
TOOL_GITOPS_DRIFT_INSPECT = "gitops.drift.inspect"

ALL_GITOPS_TOOLS = (
    TOOL_GITOPS_APP_STATUS,
    TOOL_GITOPS_APP_DIFF,
    TOOL_GITOPS_SOURCE_REVISION,
    TOOL_GITOPS_DRIFT_INSPECT,
)
