OPENMINION_BROWSER_DEFAULT_PROVIDER_ENV = "OPENMINION_BROWSER_DEFAULT_PROVIDER"
DEFAULT_BROWSER_SESSION_STATE_RELATIVE_PATH = "browser/session_state.json"
BLANK_BROWSER_URLS: tuple[str, ...] = ("about:blank", "about:newtab", "about:home")
NEW_TAB_URL_PREFIXES: tuple[str, ...] = ("chrome://newtab", "edge://newtab")
BROWSER_PROVIDER_AUTO = "auto"
BROWSER_PROVIDER_PINCHTAB = "pinchtab"
BROWSER_PROVIDER_PLAYWRIGHT = "playwright"
BROWSER_SNAPSHOT_MODE_AUTO = "auto"
BROWSER_SNAPSHOT_MODE_REFS = "refs"
BROWSER_SNAPSHOT_MODE_A11Y = "a11y"
BROWSER_SNAPSHOT_MODE_DOM = "dom"
BROWSER_SNAPSHOT_MODE_MIN = "min"
BROWSER_TEXT_MODE_READABILITY = "readability"
BROWSER_OUTPUT_FORMAT_PNG = "png"
BROWSER_OUTPUT_FORMAT_JPG = "jpg"
BROWSER_OUTPUT_FORMAT_PDF = "pdf"
BROWSER_OUTPUT_FORMAT_AUTO = "auto"
BROWSER_DAEMON_STATUS_STOPPED = "stopped"
BROWSER_DAEMON_STATUS_KILLED = "killed"

__all__ = [
    "BLANK_BROWSER_URLS",
    "BROWSER_DAEMON_STATUS_KILLED",
    "BROWSER_DAEMON_STATUS_STOPPED",
    "BROWSER_OUTPUT_FORMAT_JPG",
    "BROWSER_OUTPUT_FORMAT_AUTO",
    "BROWSER_OUTPUT_FORMAT_PDF",
    "BROWSER_OUTPUT_FORMAT_PNG",
    "BROWSER_PROVIDER_AUTO",
    "BROWSER_PROVIDER_PINCHTAB",
    "BROWSER_PROVIDER_PLAYWRIGHT",
    "BROWSER_SNAPSHOT_MODE_A11Y",
    "BROWSER_SNAPSHOT_MODE_AUTO",
    "BROWSER_SNAPSHOT_MODE_DOM",
    "BROWSER_SNAPSHOT_MODE_MIN",
    "BROWSER_SNAPSHOT_MODE_REFS",
    "BROWSER_TEXT_MODE_READABILITY",
    "DEFAULT_BROWSER_SESSION_STATE_RELATIVE_PATH",
    "NEW_TAB_URL_PREFIXES",
    "OPENMINION_BROWSER_DEFAULT_PROVIDER_ENV",
]
