SERVICES_STATE_DIRNAME = "state"
SERVICES_STATE_DB_FILENAME = "openminion.db"
SERVICES_CONFIG_SUBDIR = "config"
SERVICES_SESSION_CONTEXT_SUBDIR = "session-context"
SERVICES_TOOL_RUNTIME_SUBDIR = "tool-runtime"
SERVICES_MEMORY_SUBDIR = "memory"
SERVICES_MEMORY_DB_FILENAME = "memory.db"
SERVICES_IDENTITY_SUBDIR = "identity"
SERVICES_IDENTITY_DB_FILENAME = "identity.db"
SERVICES_PLUGIN_MANIFEST_SUFFIX = ".manifest.json"
SERVICES_PLUGIN_MANIFEST_GLOB = f"*{SERVICES_PLUGIN_MANIFEST_SUFFIX}"

__all__ = [
    "SERVICES_CONFIG_SUBDIR",
    "SERVICES_IDENTITY_DB_FILENAME",
    "SERVICES_IDENTITY_SUBDIR",
    "SERVICES_MEMORY_DB_FILENAME",
    "SERVICES_MEMORY_SUBDIR",
    "SERVICES_PLUGIN_MANIFEST_GLOB",
    "SERVICES_PLUGIN_MANIFEST_SUFFIX",
    "SERVICES_SESSION_CONTEXT_SUBDIR",
    "SERVICES_STATE_DB_FILENAME",
    "SERVICES_STATE_DIRNAME",
    "SERVICES_TOOL_RUNTIME_SUBDIR",
]
