MEMORY_CAPSULE_STRATEGY_DYNAMIC_TURN = "dynamic_turn"
MEMORY_CAPSULE_STRATEGY_FROZEN_SESSION = "frozen_session"
MEMORY_CAPSULE_STRATEGY_REFRESH_ON_WRITE = "refresh_on_write"
MEMORY_CAPSULE_STRATEGY_OFF = "off"
MEMORY_CAPSULE_CACHEABLE_STRATEGIES = frozenset(
    {
        MEMORY_CAPSULE_STRATEGY_FROZEN_SESSION,
        MEMORY_CAPSULE_STRATEGY_REFRESH_ON_WRITE,
    }
)

SERVICES_PROJECT_ID_ENV = "OPENMINION_PROJECT_ID"

__all__ = [
    "MEMORY_CAPSULE_CACHEABLE_STRATEGIES",
    "MEMORY_CAPSULE_STRATEGY_DYNAMIC_TURN",
    "MEMORY_CAPSULE_STRATEGY_FROZEN_SESSION",
    "MEMORY_CAPSULE_STRATEGY_OFF",
    "MEMORY_CAPSULE_STRATEGY_REFRESH_ON_WRITE",
    "SERVICES_PROJECT_ID_ENV",
]
