from openminion.tools.fetch.constants import (
    FETCH_BACKEND_AUTO,
    FETCH_EXTRACT_MODE_NONE,
    FETCH_PROVIDER_ID_CORE_HTTP,
    FETCH_PROVIDER_ID_SCRAPLING,
    FETCH_SCRAPLING_MODE_DYNAMIC,
    FETCH_SCRAPLING_MODE_STATIC,
    FETCH_SCRAPLING_MODE_STEALTH,
    FETCH_SCRAPLING_MODES,
)

FETCH_SCRAPLING_PROVIDER_ID = FETCH_PROVIDER_ID_SCRAPLING

__all__ = [
    "FETCH_BACKEND_AUTO",
    "FETCH_EXTRACT_MODE_NONE",
    "FETCH_PROVIDER_ID_CORE_HTTP",
    "FETCH_SCRAPLING_MODE_DYNAMIC",
    "FETCH_SCRAPLING_MODE_STATIC",
    "FETCH_SCRAPLING_MODE_STEALTH",
    "FETCH_SCRAPLING_MODES",
    "FETCH_SCRAPLING_PROVIDER_ID",
]
