RUNTIME_POLICY_OUTCOME_ALLOW = "allow"
RUNTIME_POLICY_OUTCOME_DENY = "deny"
RUNTIME_POLICY_OUTCOME_ALLOW_WITH_CONSTRAINTS = "allow_with_constraints"
RUNTIME_POLICY_OUTCOME_CONFIRM = "confirm"

RUNTIME_TOOL_OUTCOME_COMPLETED = "completed"
RUNTIME_TOOL_OUTCOME_BLOCKED = "blocked"
RUNTIME_TOOL_OUTCOME_ERROR = "error"
RUNTIME_TOOL_OUTCOME_CACHED = "cached"

RUNTIME_TURN_STATUS_STARTED = "started"
RUNTIME_TURN_STATUS_COMPLETED = "completed"
RUNTIME_TURN_STATUS_CANCELLED = "cancelled"
RUNTIME_TURN_STATUS_FAILED = "failed"
RUNTIME_TURN_STATUS_ERROR = "error"

RUNTIME_NET_MODE_DENY = "deny"
RUNTIME_NET_MODE_ALLOW = "allow"

DEFAULT_CONFIG_FILENAME = "runtime.yaml"
