UTILITY_ALLOWED_FORMATS: tuple[str, ...] = ("iso", "epoch")
UTILITY_MAX_AST_NODES = 128
UTILITY_MAX_ABS_VALUE = 10**12

__all__ = [
    "UTILITY_ALLOWED_FORMATS",
    "UTILITY_MAX_ABS_VALUE",
    "UTILITY_MAX_AST_NODES",
]
