FETCH_FIRECRAWL_PROVIDER_ID = "firecrawl"
FIRECRAWL_SCRAPE_API_PATH = "/v2/scrape"

# Shared Firecrawl env names. The canonical registry lives in
FIRECRAWL_API_KEY_ENV = "FIRECRAWL_API_KEY"
FIRECRAWL_API_URL_ENV = "FIRECRAWL_API_URL"
FIRECRAWL_TIMEOUT_SECONDS_ENV = "FIRECRAWL_TIMEOUT_SECONDS"
DEFAULT_FIRECRAWL_API_URL = "https://api.firecrawl.dev"
DEFAULT_FIRECRAWL_TIMEOUT_SECONDS = 20.0

# Supported v1 Firecrawl scrape `formats` subset (spec §4.6).
SUPPORTED_FIRECRAWL_FORMATS = ("markdown", "html", "rawHtml", "links")
DEFAULT_FIRECRAWL_FORMATS = ("markdown",)


__all__ = [
    "DEFAULT_FIRECRAWL_API_URL",
    "DEFAULT_FIRECRAWL_FORMATS",
    "DEFAULT_FIRECRAWL_TIMEOUT_SECONDS",
    "FETCH_FIRECRAWL_PROVIDER_ID",
    "FIRECRAWL_API_KEY_ENV",
    "FIRECRAWL_API_URL_ENV",
    "FIRECRAWL_SCRAPE_API_PATH",
    "FIRECRAWL_TIMEOUT_SECONDS_ENV",
    "SUPPORTED_FIRECRAWL_FORMATS",
]
