from openminion.modules.runtime.constants import (
    DAYTONA_DEFAULT_API_KEY_ENV,
    DAYTONA_DEFAULT_WORKSPACE_IMAGE,
    SANDBOX_ERROR_CODES,
    SANDBOX_NETWORK_DENIED,
    SANDBOX_RESOURCE_LIMIT,
    SANDBOX_UNAVAILABLE,
)

ACTION_POLICY_MODE_DISABLED = "disabled"
ACTION_POLICY_MODE_ENFORCE = "enforce"
ACTION_POLICY_MODE_ENFORCE_SAFE = "enforce_safe"
ACTION_POLICY_MODE_DEFAULT_ALIAS = "auto"
ACTION_POLICY_MODE_BYPASS_ALIASES = frozenset({"bypass"})
ACTION_POLICY_MODE_AUTO_ALIASES = frozenset({ACTION_POLICY_MODE_DEFAULT_ALIAS})
ACTION_POLICY_MODE_ENFORCE_ALIASES = frozenset({"ask"})

PLUGIN_TRUST_TIER_LOCAL_DEV = "local-dev"
PLUGIN_TRUST_TIER_VERIFIED = "verified"
PLUGIN_TRUST_TIER_RESTRICTED = "restricted"
PLUGIN_TRUST_TIER_VALUES = (
    PLUGIN_TRUST_TIER_LOCAL_DEV,
    PLUGIN_TRUST_TIER_VERIFIED,
    PLUGIN_TRUST_TIER_RESTRICTED,
)
PLUGIN_TRUST_TIERS = frozenset(PLUGIN_TRUST_TIER_VALUES)

PLUGIN_PROVENANCE_SOURCE_BUILTIN = "builtin"
PLUGIN_PROVENANCE_SOURCE_LOCAL_PATH = "local-path"
PLUGIN_PROVENANCE_SOURCE_GIT = "git"
PLUGIN_PROVENANCE_SOURCE_REGISTRY = "registry"
PLUGIN_PROVENANCE_SOURCE_PACKAGE = "package"
PLUGIN_PROVENANCE_SOURCE_VALUES = (
    PLUGIN_PROVENANCE_SOURCE_BUILTIN,
    PLUGIN_PROVENANCE_SOURCE_LOCAL_PATH,
    PLUGIN_PROVENANCE_SOURCE_GIT,
    PLUGIN_PROVENANCE_SOURCE_REGISTRY,
    PLUGIN_PROVENANCE_SOURCE_PACKAGE,
)
PLUGIN_PROVENANCE_SOURCES = frozenset(PLUGIN_PROVENANCE_SOURCE_VALUES)

A2A_DELEGATE_DEFAULT_TIMEOUT_SECONDS = 120

__all__ = [
    "ACTION_POLICY_MODE_BYPASS_ALIASES",
    "ACTION_POLICY_MODE_AUTO_ALIASES",
    "ACTION_POLICY_MODE_DEFAULT_ALIAS",
    "ACTION_POLICY_MODE_DISABLED",
    "ACTION_POLICY_MODE_ENFORCE",
    "ACTION_POLICY_MODE_ENFORCE_SAFE",
    "ACTION_POLICY_MODE_ENFORCE_ALIASES",
    "A2A_DELEGATE_DEFAULT_TIMEOUT_SECONDS",
    "DAYTONA_DEFAULT_API_KEY_ENV",
    "DAYTONA_DEFAULT_WORKSPACE_IMAGE",
    "PLUGIN_PROVENANCE_SOURCES",
    "PLUGIN_PROVENANCE_SOURCE_BUILTIN",
    "PLUGIN_PROVENANCE_SOURCE_GIT",
    "PLUGIN_PROVENANCE_SOURCE_LOCAL_PATH",
    "PLUGIN_PROVENANCE_SOURCE_PACKAGE",
    "PLUGIN_PROVENANCE_SOURCE_REGISTRY",
    "PLUGIN_PROVENANCE_SOURCE_VALUES",
    "PLUGIN_TRUST_TIERS",
    "PLUGIN_TRUST_TIER_LOCAL_DEV",
    "PLUGIN_TRUST_TIER_RESTRICTED",
    "PLUGIN_TRUST_TIER_VERIFIED",
    "PLUGIN_TRUST_TIER_VALUES",
    "SANDBOX_ERROR_CODES",
    "SANDBOX_NETWORK_DENIED",
    "SANDBOX_RESOURCE_LIMIT",
    "SANDBOX_UNAVAILABLE",
]
API_METRICS_TOKEN_ENV = "OPENMINION_API_METRICS_TOKEN"
API_METRICS_TOKEN_HEADER = "X-Metrics-Token"
