from openminion.tools.constants import (
    OPENMINION_POLICY_PATH_ENV as EXEC_POLICY_PATH_ENV,
)

EXEC_ENABLE_HOST_EXEC_ENV = "OPENMINION_TOOL_EXEC_ENABLE_HOST_EXEC"
EXEC_DEBUG_PARSE_EVENT_ENV = "OPENMINION_TOOL_EXEC_DEBUG_PARSE_EVENT"
EXEC_ALLOWLIST_PATHS_ENV = "OPENMINION_TOOL_EXEC_ALLOWLIST_PATHS"

EXEC_AGENT_ID_ENV = "OPENMINION_AGENT_ID"
EXEC_SAFE_BINS_ENV = "OPENMINION_TOOL_EXEC_SAFE_BINS"
EXEC_SAFE_BIN_TRUSTED_DIRS_ENV = "OPENMINION_TOOL_EXEC_SAFE_BIN_TRUSTED_DIRS"

EXEC_ARTIFACT_THRESHOLD_BYTES = 4096
EXEC_MAX_PREVIEW_CHARS = 4000
EXEC_SAFE_BINS_DEFAULT: frozenset[str] = frozenset(
    {"cat", "head", "tail", "grep", "sed", "awk", "tr", "cut", "sort", "uniq", "wc"}
)
EXEC_SAFE_BIN_TRUSTED_DIRS_DEFAULT: frozenset[str] = frozenset(
    {"/bin", "/usr/bin", "/usr/local/bin"}
)
EXEC_DENY_HOST_ENV_PREFIXES: tuple[str, ...] = ("LD_", "DYLD_")
EXEC_APPROVAL_PENDING_STATUSES: frozenset[str] = frozenset({"on-miss", "always"})

__all__ = [
    "EXEC_AGENT_ID_ENV",
    "EXEC_ALLOWLIST_PATHS_ENV",
    "EXEC_APPROVAL_PENDING_STATUSES",
    "EXEC_ARTIFACT_THRESHOLD_BYTES",
    "EXEC_DEBUG_PARSE_EVENT_ENV",
    "EXEC_DENY_HOST_ENV_PREFIXES",
    "EXEC_ENABLE_HOST_EXEC_ENV",
    "EXEC_MAX_PREVIEW_CHARS",
    "EXEC_POLICY_PATH_ENV",
    "EXEC_SAFE_BINS_DEFAULT",
    "EXEC_SAFE_BIN_TRUSTED_DIRS_DEFAULT",
    "EXEC_SAFE_BINS_ENV",
    "EXEC_SAFE_BIN_TRUSTED_DIRS_ENV",
]
