TAVILY_API_URL_ENV = "TAVILY_API_URL"
TAVILY_TIMEOUT_SECONDS_ENV = "TAVILY_TIMEOUT_SECONDS"
DEFAULT_TAVILY_API_URL = "https://api.tavily.com/search"
DEFAULT_TAVILY_MAX_SEARCH_RETRIES = 2
DEFAULT_TAVILY_SEARCH_RETRY_BACKOFF: tuple[float, ...] = (0.5, 1.0)

__all__ = [
    "DEFAULT_TAVILY_API_URL",
    "DEFAULT_TAVILY_MAX_SEARCH_RETRIES",
    "DEFAULT_TAVILY_SEARCH_RETRY_BACKOFF",
    "TAVILY_API_URL_ENV",
    "TAVILY_TIMEOUT_SECONDS_ENV",
]
