TAVILY_API_URL_ENV = "TAVILY_API_URL"
TAVILY_TIMEOUT_SECONDS_ENV = "TAVILY_TIMEOUT_SECONDS"
DEFAULT_TAVILY_API_URL = "https://api.tavily.com/search"
DEFAULT_TAVILY_MAX_SEARCH_RETRIES = 2
DEFAULT_TAVILY_SEARCH_RETRY_BACKOFF: tuple[float, ...] = (0.5, 1.0)
TAVILY_SEARCH_DEPTH_BASIC = "basic"
TAVILY_SEARCH_DEPTH_ADVANCED = "advanced"
TAVILY_SEARCH_DEPTH_VALUES: frozenset[str] = frozenset(
    {TAVILY_SEARCH_DEPTH_BASIC, TAVILY_SEARCH_DEPTH_ADVANCED}
)

__all__ = [
    "DEFAULT_TAVILY_API_URL",
    "DEFAULT_TAVILY_MAX_SEARCH_RETRIES",
    "DEFAULT_TAVILY_SEARCH_RETRY_BACKOFF",
    "TAVILY_SEARCH_DEPTH_ADVANCED",
    "TAVILY_SEARCH_DEPTH_BASIC",
    "TAVILY_SEARCH_DEPTH_VALUES",
    "TAVILY_API_URL_ENV",
    "TAVILY_TIMEOUT_SECONDS_ENV",
]
