from pathlib import Path
from openminion.base.constants import (
    OPENMINION_DATA_ROOT_ENV,
    OPENMINION_HOME_ENV,
    OPENMINION_MODULE_STANDALONE_ENV,
)

RETRIEVECTL_CONFIG_ENV = "RETRIEVECTL_CONFIG"
RETRIEVECTL_HOME_ENV = OPENMINION_HOME_ENV

DEFAULT_CONFIG_FILENAME = "retrieve.yaml"
DEFAULT_INTEGRATED_SQLITE_PATH = Path("retrieve") / "retrieve.db"
DEFAULT_INTEGRATED_BLOB_ROOT = Path("retrieve") / "blobs"
DEFAULT_STANDALONE_ROOT = Path(".retrievectl")
DEFAULT_STANDALONE_SQLITE_PATH = DEFAULT_STANDALONE_ROOT / "retrievectl.db"

__all__ = (
    "DEFAULT_CONFIG_FILENAME",
    "DEFAULT_INTEGRATED_BLOB_ROOT",
    "DEFAULT_INTEGRATED_SQLITE_PATH",
    "DEFAULT_STANDALONE_ROOT",
    "DEFAULT_STANDALONE_SQLITE_PATH",
    "OPENMINION_DATA_ROOT_ENV",
    "OPENMINION_HOME_ENV",
    "OPENMINION_MODULE_STANDALONE_ENV",
    "RETRIEVECTL_CONFIG_ENV",
    "RETRIEVECTL_HOME_ENV",
)
