TINYFISH_SEARCH_PROVIDER_ID = "tinyfish"
TINYFISH_SEARCH_DISPLAY_NAME = "TinyFish Search"
TINYFISH_SEARCH_API_URL_ENV = "TINYFISH_SEARCH_API_URL"
TINYFISH_SEARCH_TIMEOUT_SECONDS_ENV = "TINYFISH_SEARCH_TIMEOUT_SECONDS"
DEFAULT_TINYFISH_SEARCH_API_URL = "https://api.search.tinyfish.ai"
DEFAULT_TINYFISH_SEARCH_TIMEOUT_SECONDS = 20.0

__all__ = [
    "DEFAULT_TINYFISH_SEARCH_API_URL",
    "DEFAULT_TINYFISH_SEARCH_TIMEOUT_SECONDS",
    "TINYFISH_SEARCH_API_URL_ENV",
    "TINYFISH_SEARCH_DISPLAY_NAME",
    "TINYFISH_SEARCH_PROVIDER_ID",
    "TINYFISH_SEARCH_TIMEOUT_SECONDS_ENV",
]
