from typing import Literal

from openminion.tools.constants import (
    TOOL_REASON_RECORD_NOT_FOUND as LOCATION_REASON_RECORD_NOT_FOUND,
    TOOL_REASON_STORAGE_EXEC_ERROR as LOCATION_REASON_STORAGE_EXEC_ERROR,
    TOOL_REASON_STORAGE_UNAVAILABLE as LOCATION_REASON_STORAGE_UNAVAILABLE,
    TOOL_REASON_STORAGE_UNCONFIGURED as LOCATION_REASON_STORAGE_UNCONFIGURED,
)

LOCATION_SOURCE_SESSION_OVERRIDE: Literal["session.override"] = "session.override"
LOCATION_SOURCE_IDENTITY_DEFAULT: Literal["identity.default"] = "identity.default"
LOCATION_SOURCE_IP_GEO: Literal["ip.geo"] = "ip.geo"
LOCATION_SOURCE_NONE: Literal["none"] = "none"
LOCATION_SOURCE_VALUES: tuple[str, ...] = (
    LOCATION_SOURCE_SESSION_OVERRIDE,
    LOCATION_SOURCE_IDENTITY_DEFAULT,
    LOCATION_SOURCE_IP_GEO,
    LOCATION_SOURCE_NONE,
)
LOCATION_PREFER_AUTO: Literal["auto"] = "auto"
LOCATION_PREFER_IDENTITY: Literal["identity"] = "identity"
LOCATION_PREFER_IP: Literal["ip"] = "ip"
LOCATION_PREFER_SESSION: Literal["session"] = "session"
LOCATION_PRIVACY_NONE: Literal["none"] = "none"
LOCATION_PRIVACY_CITY: Literal["city"] = "city"
LOCATION_PRIVACY_REGION: Literal["region"] = "region"
LOCATION_PRIVACY_PRECISE: Literal["precise"] = "precise"
LOCATION_PRIVACY_LEVELS: tuple[str, ...] = (
    LOCATION_PRIVACY_NONE,
    LOCATION_PRIVACY_CITY,
    LOCATION_PRIVACY_REGION,
    LOCATION_PRIVACY_PRECISE,
)
LOCATION_SCOPE_ORDER: dict[str, int] = {
    "READ_ONLY": 0,
    "WRITE_SAFE": 1,
    "POWER_USER": 2,
    "UI_AUTOMATION": 3,
}

__all__ = [
    "LOCATION_PREFER_AUTO",
    "LOCATION_PREFER_IDENTITY",
    "LOCATION_PREFER_IP",
    "LOCATION_PREFER_SESSION",
    "LOCATION_PRIVACY_CITY",
    "LOCATION_PRIVACY_LEVELS",
    "LOCATION_PRIVACY_NONE",
    "LOCATION_PRIVACY_PRECISE",
    "LOCATION_PRIVACY_REGION",
    "LOCATION_REASON_RECORD_NOT_FOUND",
    "LOCATION_REASON_STORAGE_EXEC_ERROR",
    "LOCATION_REASON_STORAGE_UNAVAILABLE",
    "LOCATION_REASON_STORAGE_UNCONFIGURED",
    "LOCATION_SCOPE_ORDER",
    "LOCATION_SOURCE_IDENTITY_DEFAULT",
    "LOCATION_SOURCE_IP_GEO",
    "LOCATION_SOURCE_NONE",
    "LOCATION_SOURCE_SESSION_OVERRIDE",
    "LOCATION_SOURCE_VALUES",
]
