from openminion.tools.constants import (
    TOOL_REASON_RECORD_NOT_FOUND as LOCATION_REASON_RECORD_NOT_FOUND,
    TOOL_REASON_STORAGE_EXEC_ERROR as LOCATION_REASON_STORAGE_EXEC_ERROR,
    TOOL_REASON_STORAGE_UNAVAILABLE as LOCATION_REASON_STORAGE_UNAVAILABLE,
    TOOL_REASON_STORAGE_UNCONFIGURED as LOCATION_REASON_STORAGE_UNCONFIGURED,
)

LOCATION_SCOPE_ORDER: dict[str, int] = {
    "READ_ONLY": 0,
    "WRITE_SAFE": 1,
    "POWER_USER": 2,
    "UI_AUTOMATION": 3,
}

__all__ = [
    "LOCATION_REASON_RECORD_NOT_FOUND",
    "LOCATION_REASON_STORAGE_EXEC_ERROR",
    "LOCATION_REASON_STORAGE_UNAVAILABLE",
    "LOCATION_REASON_STORAGE_UNCONFIGURED",
    "LOCATION_SCOPE_ORDER",
]
