from openminion.base.constants import (
    OPENMINION_DATA_ROOT_ENV,
    OPENMINION_HOME_ENV,
    OPENMINION_MODULE_STANDALONE_ENV,
)
from openminion.tools.constants import OPENMINION_POLICY_PATH_ENV
from openminion.modules.paths import IDENTITY_DB_SUBPATH

OPENMINION_MODULES_ONLY_ENV = "OPENMINION_MODULES_ONLY"
OPENMINION_CONFIG_PATH_ENV = "OPENMINION_CONFIG_PATH"
OPENMINION_TAVILY_SOURCE_ENV = "OPENMINION_TAVILY_SOURCE"
OPENMINION_WEATHER_SOURCE_ENV = "OPENMINION_WEATHER_SOURCE"

TOOL_BOOTSTRAP_GATE_ALWAYS = "always"
TOOL_BOOTSTRAP_GATE_NEVER = "never"
TOOL_BOOTSTRAP_STATUS_REGISTERED = "registered"
TOOL_BOOTSTRAP_STATUS_ALREADY_REGISTERED = "already_registered"
TOOL_BOOTSTRAP_STATUS_IMPORT_ERROR = "import_error"
TOOL_BOOTSTRAP_STATUS_NO_REGISTER = "no_register"
TOOL_BOOTSTRAP_STATUS_REGISTER_FAILED = "register_failed"
TOOL_BOOTSTRAP_STATUS_REGISTRAR_FAILED = "registrar_failed"
TOOL_BOOTSTRAP_STATUS_SKIPPED_GATE = "skipped_gate"

TOOL_REDACTION_MODE_NORMAL = "normal"
TOOL_REDACTION_MODE_STRICT = "strict"
TOOL_REDACTION_MODE_OFF = "off"
TOOL_REDACTION_MODE_CHOICES: tuple[str, ...] = (
    TOOL_REDACTION_MODE_NORMAL,
    TOOL_REDACTION_MODE_STRICT,
    TOOL_REDACTION_MODE_OFF,
)

TOOL_SOURCE_MODULE_FIRST: str = "module_first"

TOOL_EXEC_SECURITY_DENY = "deny"
TOOL_EXEC_SECURITY_ALLOWLIST = "allowlist"
TOOL_EXEC_SECURITY_FULL = "full"
TOOL_EXEC_SECURITY_CHOICES: tuple[str, ...] = (
    TOOL_EXEC_SECURITY_DENY,
    TOOL_EXEC_SECURITY_ALLOWLIST,
    TOOL_EXEC_SECURITY_FULL,
)

TOOL_EXEC_ASK_OFF = "off"
TOOL_EXEC_ASK_ON_MISS = "on-miss"
TOOL_EXEC_ASK_ALWAYS = "always"
TOOL_EXEC_ASK_CHOICES: tuple[str, ...] = (
    TOOL_EXEC_ASK_OFF,
    TOOL_EXEC_ASK_ON_MISS,
    TOOL_EXEC_ASK_ALWAYS,
)

TOOL_DANGEROUS_MODE_PROMPT = "prompt"
TOOL_DANGEROUS_MODE_DENY = "deny"
TOOL_DANGEROUS_MODE_ALLOW = "allow"
TOOL_DANGEROUS_MODE_CHOICES: tuple[str, ...] = (
    TOOL_DANGEROUS_MODE_PROMPT,
    TOOL_DANGEROUS_MODE_DENY,
    TOOL_DANGEROUS_MODE_ALLOW,
)

TOOL_POLICY_ACTION_ALLOW = "allow"
TOOL_POLICY_ACTION_DENY = "deny"
TOOL_POLICY_ACTION_CONFIRM = "confirm"
TOOL_POLICY_ACTION_REQUIRE_CONFIRM = "require_confirm"

TOOL_RESULT_STATUS_OK = "ok"
TOOL_RESULT_STATUS_ERROR = "error"

PROVIDER_TOOL_CALL_DEFAULT_SOURCE = "native"

TOOL_AUDIT_WRITE_MODE_DUAL = "dual"
TOOL_AUDIT_WRITE_MODE_JSONL_ONLY = "jsonl_only"
TOOL_AUDIT_WRITE_MODE_STORAGE_ONLY = "storage_only"
TOOL_AUDIT_WRITE_MODE_OFF = "off"

DEFAULT_POLICY_FILENAME = "policy.yaml"
DEFAULT_IDENTITY_DB_SUBPATH = IDENTITY_DB_SUBPATH
DEFAULT_TOOL_RUNS_DIRNAME = "tool-runs"

__all__ = [
    "DEFAULT_IDENTITY_DB_SUBPATH",
    "DEFAULT_POLICY_FILENAME",
    "DEFAULT_TOOL_RUNS_DIRNAME",
    "OPENMINION_CONFIG_PATH_ENV",
    "OPENMINION_DATA_ROOT_ENV",
    "OPENMINION_HOME_ENV",
    "OPENMINION_MODULE_STANDALONE_ENV",
    "OPENMINION_MODULES_ONLY_ENV",
    "OPENMINION_POLICY_PATH_ENV",
    "OPENMINION_TAVILY_SOURCE_ENV",
    "OPENMINION_WEATHER_SOURCE_ENV",
    "PROVIDER_TOOL_CALL_DEFAULT_SOURCE",
    "TOOL_AUDIT_WRITE_MODE_DUAL",
    "TOOL_AUDIT_WRITE_MODE_JSONL_ONLY",
    "TOOL_AUDIT_WRITE_MODE_OFF",
    "TOOL_AUDIT_WRITE_MODE_STORAGE_ONLY",
    "TOOL_BOOTSTRAP_GATE_ALWAYS",
    "TOOL_BOOTSTRAP_GATE_NEVER",
    "TOOL_BOOTSTRAP_STATUS_ALREADY_REGISTERED",
    "TOOL_BOOTSTRAP_STATUS_IMPORT_ERROR",
    "TOOL_BOOTSTRAP_STATUS_NO_REGISTER",
    "TOOL_BOOTSTRAP_STATUS_REGISTERED",
    "TOOL_BOOTSTRAP_STATUS_REGISTER_FAILED",
    "TOOL_BOOTSTRAP_STATUS_REGISTRAR_FAILED",
    "TOOL_BOOTSTRAP_STATUS_SKIPPED_GATE",
    "TOOL_DANGEROUS_MODE_ALLOW",
    "TOOL_DANGEROUS_MODE_CHOICES",
    "TOOL_DANGEROUS_MODE_DENY",
    "TOOL_DANGEROUS_MODE_PROMPT",
    "TOOL_EXEC_ASK_ALWAYS",
    "TOOL_EXEC_ASK_CHOICES",
    "TOOL_EXEC_ASK_OFF",
    "TOOL_EXEC_ASK_ON_MISS",
    "TOOL_EXEC_SECURITY_ALLOWLIST",
    "TOOL_EXEC_SECURITY_CHOICES",
    "TOOL_EXEC_SECURITY_DENY",
    "TOOL_EXEC_SECURITY_FULL",
    "TOOL_POLICY_ACTION_ALLOW",
    "TOOL_POLICY_ACTION_CONFIRM",
    "TOOL_POLICY_ACTION_DENY",
    "TOOL_POLICY_ACTION_REQUIRE_CONFIRM",
    "TOOL_REDACTION_MODE_CHOICES",
    "TOOL_REDACTION_MODE_NORMAL",
    "TOOL_REDACTION_MODE_OFF",
    "TOOL_REDACTION_MODE_STRICT",
    "TOOL_RESULT_STATUS_ERROR",
    "TOOL_RESULT_STATUS_OK",
]
