"""Lazy export table for the tool package."""

from __future__ import annotations

from typing import Any

PUBLIC_EXPORTS = [
    "__version__",
    "AllowAllPolicyHook",
    "BindingResolution",
    "CONTRACT_VERSION_PATTERN",
    "DEFAULT_POLICY",
    "DenyHighRiskWithoutTagPolicyHook",
    "PLUGIN_CONTRACT_VERSION",
    "Policy",
    "RuntimeBindingPolicy",
    "RuntimeBootstrap",
    "RuntimeContext",
    "Tool",
    "ToolBindingPolicyManager",
    "ToolExecutionBatch",
    "ToolExecutionContext",
    "ToolExecutionPolicy",
    "ToolExecutionResult",
    "ToolModuleRegistrar",
    "ToolPolicyProfile",
    "ToolRegisterContext",
    "ToolRegistry",
    "ToolRegistryManager",
    "ToolRuntime",
    "ToolSpec",
    "TOOL_RESULT_BLAST_RADIUS_KEY",
    "_MODULES_ONLY",
    "_TAVILY_SOURCE",
    "_WEATHER_SOURCE",
    "build_default_tool_registry",
    "build_default_tool_registry_debug_report",
    "build_runtime_bootstrap",
    "build_runtime_repositories",
    "blast_radius_requires_verification",
    "canonical_tool_name",
    "create_run_root",
    "new_run_id",
    "preferred_artifact_ref",
    "reorder_runtime_chain",
    "resolve_binding_for_call",
    "tool_result_blast_radius",
    "tool_family_for_argument_repair",
    "validate_plugin_contract",
]

LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "bootstrap": (".bootstrap", "__module__"),
    "cli": (".cli", "__module__"),
    "constants": (".constants", "__module__"),
    "OPENMINION_VERSION": (".facade", "OPENMINION_VERSION"),
    "TOOL_BOOTSTRAP_STATUS_ALREADY_REGISTERED": (
        ".constants",
        "TOOL_BOOTSTRAP_STATUS_ALREADY_REGISTERED",
    ),
    "TOOL_BOOTSTRAP_STATUS_REGISTERED": (
        ".constants",
        "TOOL_BOOTSTRAP_STATUS_REGISTERED",
    ),
    "ContractProtocol": (".interfaces", "ContractProtocol"),
    "ContractValidator": (".interfaces", "ContractValidator"),
    "PluginContract": (".interfaces", "PluginContract"),
    "PluginContractError": (".interfaces", "PluginContractError"),
    "ToolErrorEnvelope": (".interfaces", "ToolErrorEnvelope"),
    "ToolRequestEnvelope": (".interfaces", "ToolRequestEnvelope"),
    "ToolResultEnvelope": (".interfaces", "ToolResultEnvelope"),
    "ArtifactRef": (".plugin_contract", "ArtifactRef"),
    "CASArtifactSink": (".plugin_contract", "CASArtifactSink"),
    "HealthStatus": (".plugin_contract", "HealthStatus"),
    "MemoryArtifactSink": (".plugin_contract", "MemoryArtifactSink"),
    "MemoryEventSink": (".plugin_contract", "MemoryEventSink"),
    "MethodSchema": (".plugin_contract", "MethodSchema"),
    "PolicyDecision": (".plugin_contract", "PolicyDecision"),
    "PolicyHook": (".plugin_contract", "PolicyHook"),
    "ToolCapabilities": (".plugin_contract", "ToolCapabilities"),
    "ToolContext": (".plugin_contract", "ToolContext"),
    "ToolDefinition": (".plugin_contract", "ToolDefinition"),
    "ToolDescriptor": (".plugin_contract", "ToolDescriptor"),
    "ToolError": (".plugin_contract", "ToolError"),
    "ToolInvocation": (".plugin_contract", "ToolInvocation"),
    "ToolMethod": (".plugin_contract", "ToolMethod"),
    "ToolPlugin": (".plugin_contract", "ToolPlugin"),
    "ToolResult": (".plugin_contract", "ToolResult"),
    "ToolSchemaBundle": (".plugin_contract", "ToolSchemaBundle"),
    "build_default_tool_registry_manager": (
        ".runtime.manager",
        "build_default_tool_registry_manager",
    ),
    "__version__": (".facade", "__version__"),
    "AllowAllPolicyHook": (".runtime.plugin", "AllowAllPolicyHook"),
    "BindingResolution": (".runtime.dispatch", "BindingResolution"),
    "CONTRACT_VERSION_PATTERN": (".interfaces", "CONTRACT_VERSION_PATTERN"),
    "DEFAULT_POLICY": (".runtime.policy", "DEFAULT_POLICY"),
    "DenyHighRiskWithoutTagPolicyHook": (
        ".runtime.plugin",
        "DenyHighRiskWithoutTagPolicyHook",
    ),
    "PLUGIN_CONTRACT_VERSION": (".interfaces", "PLUGIN_CONTRACT_VERSION"),
    "Policy": (".runtime.policy", "Policy"),
    "RuntimeBindingPolicy": (".runtime.policy", "RuntimeBindingPolicy"),
    "RuntimeBootstrap": (".bootstrap", "RuntimeBootstrap"),
    "RuntimeContext": (".runtime", "RuntimeContext"),
    "Tool": (".base", "Tool"),
    "ToolBindingPolicyManager": (".runtime.policy", "ToolBindingPolicyManager"),
    "ToolExecutionBatch": (".registry", "ToolExecutionBatch"),
    "ToolExecutionContext": (".base", "ToolExecutionContext"),
    "ToolExecutionPolicy": (".base", "ToolExecutionPolicy"),
    "ToolExecutionResult": (".base", "ToolExecutionResult"),
    "ToolModuleRegistrar": (".runtime.registrar", "ToolModuleRegistrar"),
    "ToolPolicyProfile": (".registry", "ToolPolicyProfile"),
    "ToolRegisterContext": (".runtime.registrar", "ToolRegisterContext"),
    "ToolRegistry": (".registry", "ToolRegistry"),
    "ToolRegistryManager": (".runtime.manager", "ToolRegistryManager"),
    "ToolRuntime": (".runtime.plugin", "ToolRuntime"),
    "ToolSpec": (".registry", "ToolSpec"),
    "TOOL_RESULT_BLAST_RADIUS_KEY": (
        ".runtime.blast_radius",
        "TOOL_RESULT_BLAST_RADIUS_KEY",
    ),
    "_MODULES_ONLY": (".facade", "_MODULES_ONLY"),
    "_TAVILY_SOURCE": (".facade", "_TAVILY_SOURCE"),
    "_WEATHER_SOURCE": (".facade", "_WEATHER_SOURCE"),
    "build_default_tool_registry": (".facade", "build_default_tool_registry"),
    "build_default_tool_registry_debug_report": (
        ".facade",
        "build_default_tool_registry_debug_report",
    ),
    "build_runtime_bootstrap": (".bootstrap", "build_runtime_bootstrap"),
    "build_runtime_repositories": (".runtime", "build_runtime_repositories"),
    "blast_radius_requires_verification": (
        ".runtime.blast_radius",
        "blast_radius_requires_verification",
    ),
    "canonical_tool_name": (".runtime.policy", "canonical_tool_name"),
    "create_run_root": (".runtime", "create_run_root"),
    "new_run_id": (".runtime", "new_run_id"),
    "preferred_artifact_ref": (".runtime", "preferred_artifact_ref"),
    "reorder_runtime_chain": (".runtime.policy", "reorder_runtime_chain"),
    "resolve_binding_for_call": (".runtime.dispatch", "resolve_binding_for_call"),
    "tool_result_blast_radius": (".runtime.blast_radius", "tool_result_blast_radius"),
    "tool_family_for_argument_repair": (
        ".runtime.argument_repair",
        "tool_family_for_argument_repair",
    ),
    "validate_plugin_contract": (".interfaces", "validate_plugin_contract"),
}


def resolve_lazy_export(*, package_name: str, name: str) -> Any:
    target = LAZY_EXPORTS.get(name)
    if not target:
        raise AttributeError(name)
    module_name, attr_name = target
    module = __import__(package_name + module_name, fromlist=[attr_name])
    if attr_name == "__module__":
        return module
    return getattr(module, attr_name)
