from openminion.modules.tool import PLUGIN_CONTRACT_VERSION

OPS_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION

TOOL_OPS_TARGET_LIST = "ops.target.list"
TOOL_OPS_TARGET_INSPECT = "ops.target.inspect"
TOOL_OPS_HOST_SNAPSHOT = "ops.host.snapshot"
TOOL_OPS_SERVICE_INSPECT = "ops.service.inspect"
TOOL_OPS_LOGS_QUERY = "ops.logs.query"
TOOL_OPS_NETWORK_INSPECT = "ops.network.inspect"
TOOL_OPS_COMMAND_OBSERVE = "ops.command.observe"
TOOL_OPS_JOB_INSPECT = "ops.job.inspect"
TOOL_OPS_JOB_CANCEL = "ops.job.cancel"

ALL_OPS_TOOLS = (
    TOOL_OPS_TARGET_LIST,
    TOOL_OPS_TARGET_INSPECT,
    TOOL_OPS_HOST_SNAPSHOT,
    TOOL_OPS_SERVICE_INSPECT,
    TOOL_OPS_LOGS_QUERY,
    TOOL_OPS_NETWORK_INSPECT,
    TOOL_OPS_COMMAND_OBSERVE,
    TOOL_OPS_JOB_INSPECT,
    TOOL_OPS_JOB_CANCEL,
)
