from openminion.tools.constants import (
    TOOL_REASON_STORAGE_EXEC_ERROR as TIME_REASON_STORAGE_EXEC_ERROR,
    TOOL_REASON_STORAGE_UNAVAILABLE as TIME_REASON_STORAGE_UNAVAILABLE,
    TOOL_REASON_STORAGE_UNCONFIGURED as TIME_REASON_STORAGE_UNCONFIGURED,
)

OPENMINION_TIMEZONE_ENV = "OPENMINION_TIMEZONE"

DEFAULT_PARSE_TIMEZONE = "UTC"
DEFAULT_NEXT_CRON_COUNT = 3
MAX_NEXT_CRON_COUNT = 50
TIME_DIFF_UNIT_SECONDS = "seconds"
TIME_DIFF_UNIT_MINUTES = "minutes"
TIME_DIFF_UNIT_HOURS = "hours"
TIME_DIFF_UNIT_DAYS = "days"
TIME_DIFF_UNITS: tuple[str, ...] = (
    TIME_DIFF_UNIT_SECONDS,
    TIME_DIFF_UNIT_MINUTES,
    TIME_DIFF_UNIT_HOURS,
    TIME_DIFF_UNIT_DAYS,
)
TIME_FORMAT_ISO = "iso"
TIME_FORMAT_RFC3339 = "rfc3339"
TIME_FORMAT_DATE = "date"
TIME_FORMAT_TIME = "time"
TIME_FORMAT_DATETIME = "datetime"
TIME_FORMAT_CUSTOM = "custom"
TIME_FORMATS: tuple[str, ...] = (
    TIME_FORMAT_ISO,
    TIME_FORMAT_RFC3339,
    TIME_FORMAT_DATE,
    TIME_FORMAT_TIME,
    TIME_FORMAT_DATETIME,
    TIME_FORMAT_CUSTOM,
)
TIMEZONE_META_KEYS: tuple[str, ...] = (
    "timezone",
    "tz",
    "identity_timezone",
    "profile_timezone",
    "user_timezone",
)

__all__ = [
    "DEFAULT_NEXT_CRON_COUNT",
    "DEFAULT_PARSE_TIMEZONE",
    "MAX_NEXT_CRON_COUNT",
    "OPENMINION_TIMEZONE_ENV",
    "TIME_DIFF_UNIT_DAYS",
    "TIME_DIFF_UNIT_HOURS",
    "TIME_DIFF_UNIT_MINUTES",
    "TIME_DIFF_UNIT_SECONDS",
    "TIME_DIFF_UNITS",
    "TIME_FORMAT_CUSTOM",
    "TIME_FORMAT_DATE",
    "TIME_FORMAT_DATETIME",
    "TIME_FORMAT_ISO",
    "TIME_FORMAT_RFC3339",
    "TIME_FORMAT_TIME",
    "TIME_FORMATS",
    "TIMEZONE_META_KEYS",
    "TIME_REASON_STORAGE_EXEC_ERROR",
    "TIME_REASON_STORAGE_UNAVAILABLE",
    "TIME_REASON_STORAGE_UNCONFIGURED",
]
