from openminion.tools.constants import (
    TOOL_REASON_STORAGE_EXEC_ERROR as TIME_REASON_STORAGE_EXEC_ERROR,
    TOOL_REASON_STORAGE_UNAVAILABLE as TIME_REASON_STORAGE_UNAVAILABLE,
    TOOL_REASON_STORAGE_UNCONFIGURED as TIME_REASON_STORAGE_UNCONFIGURED,
)

OPENMINION_TIMEZONE_ENV = "OPENMINION_TIMEZONE"

DEFAULT_PARSE_TIMEZONE = "UTC"
DEFAULT_NEXT_CRON_COUNT = 3
MAX_NEXT_CRON_COUNT = 50
TIMEZONE_META_KEYS: tuple[str, ...] = (
    "timezone",
    "tz",
    "identity_timezone",
    "profile_timezone",
    "user_timezone",
)

__all__ = [
    "DEFAULT_NEXT_CRON_COUNT",
    "DEFAULT_PARSE_TIMEZONE",
    "MAX_NEXT_CRON_COUNT",
    "OPENMINION_TIMEZONE_ENV",
    "TIMEZONE_META_KEYS",
    "TIME_REASON_STORAGE_EXEC_ERROR",
    "TIME_REASON_STORAGE_UNAVAILABLE",
    "TIME_REASON_STORAGE_UNCONFIGURED",
]
