OPENMINION_COLOR_PROMPT_ENV = "OPENMINION_COLOR_PROMPT"
OPENMINION_CONVERSATION_ID_ENV = "OPENMINION_CONVERSATION_ID"
OPENMINION_DISABLE_SKILL_ENV = "OPENMINION_DISABLE_SKILL"
OPENMINION_SKILL_LOCAL_FALLBACK_ENV = "OPENMINION_SKILL_LOCAL_FALLBACK"
OPENMINION_THEME_VARIANT_ENV = "OPENMINION_THEME_VARIANT"

OPENMINION_FOCUS_GREETING_ENV = "OPENMINION_FOCUS_GREETING"
OPENMINION_FOCUS_EXAMPLE_PROMPTS_ENV = "OPENMINION_FOCUS_EXAMPLE_PROMPTS"
OPENMINION_FOCUS_BELL_ENV = "OPENMINION_FOCUS_BELL"

CLI_TRUTHY_ENV_VALUES = frozenset({"1", "true", "yes", "on"})
CLI_COLOR_PROMPT_TRUE_VALUES = frozenset({*CLI_TRUTHY_ENV_VALUES, "always"})
CLI_THEME_VARIANTS = frozenset({"balanced", "high_contrast"})
CLI_DEFAULT_THEME_VARIANT = "balanced"
CLI_THEME_VERSION = "2.0"
CLI_DEFAULT_TIME_SESSION = "time-cli"
CLI_HELP_MACHINE_READABLE_OUTPUT = "Print machine-readable output"
CLI_HELP_SESSION_ID_FOR_TOOL_LOGS = "Session id for tool logs"

__all__ = [
    "CLI_THEME_VERSION",
    "CLI_DEFAULT_TIME_SESSION",
    "CLI_COLOR_PROMPT_TRUE_VALUES",
    "CLI_DEFAULT_THEME_VARIANT",
    "CLI_HELP_MACHINE_READABLE_OUTPUT",
    "CLI_HELP_SESSION_ID_FOR_TOOL_LOGS",
    "CLI_THEME_VARIANTS",
    "CLI_TRUTHY_ENV_VALUES",
    "OPENMINION_COLOR_PROMPT_ENV",
    "OPENMINION_CONVERSATION_ID_ENV",
    "OPENMINION_DISABLE_SKILL_ENV",
    "OPENMINION_FOCUS_BELL_ENV",
    "OPENMINION_FOCUS_EXAMPLE_PROMPTS_ENV",
    "OPENMINION_FOCUS_GREETING_ENV",
    "OPENMINION_SKILL_LOCAL_FALLBACK_ENV",
    "OPENMINION_THEME_VARIANT_ENV",
]
