# Vocabulary validation requires every emitted termination_reason here.

from openminion.modules.prompting.continuation import TOOL_LOOP_CONTINUE_PROMPT

TERMINATION_REASON_TASK_COMPLETE = "task_complete"
TERMINATION_REASON_TOOL_FINAL = "tool_final"
TERMINATION_REASON_TOOL_DIRECT = "tool_direct"
TERMINATION_REASON_PASSED_GATE = "passed_gate"
TERMINATION_REASON_CONDITION_MET = "condition_met"

TERMINATION_REASON_TOOL_LOOP_MAX_STEPS = "tool_loop_max_steps"
TERMINATION_REASON_ITERATION_CAP = "iteration_cap"
TERMINATION_REASON_BUDGET_EXHAUSTED_WITH_PARTIAL_RESULT = (
    "budget_exhausted_with_partial_result"
)
TERMINATION_REASON_CONTEXT_EXHAUSTED = "context_exhausted"
TERMINATION_REASON_TIMEOUT = "timeout"
TERMINATION_REASON_TIME_BUDGET_EXCEEDED = "time_budget_exceeded"

TERMINATION_REASON_CAPABILITY_TOOL_UNAVAILABLE = "capability_tool_unavailable"
TERMINATION_REASON_FORCED_TOOL_UNAVAILABLE = "forced_tool_unavailable"
TERMINATION_REASON_BLOCKED_CAP = "blocked_cap"
TERMINATION_REASON_BLOCKED_NOVEL_FAILURE = "blocked_novel_failure"

TERMINATION_REASON_TOOL_NO_SUCCESS = "tool_no_success"
TERMINATION_REASON_MODEL_FINAL = "model_final"
TERMINATION_REASON_TOOL_UNAVAILABLE_FINAL = "tool_unavailable_final"
TERMINATION_REASON_DUPLICATE_TOOL_CALLS = "duplicate_tool_calls"
TERMINATION_REASON_FINALIZATION_CONTRACT_MISSING = "finalization_contract_missing"
TERMINATION_REASON_EMPTY_PROVIDER_RESPONSE = "empty_provider_response"
TERMINATION_REASON_REPEATED_FAILURE_STALLED = "repeated_failure_stalled"
TERMINATION_REASON_LOOP_NO_PROGRESS = "loop_no_progress"
TERMINATION_REASON_TOOL_ARG_EXHAUSTED = "tool_arg_exhausted"
TERMINATION_REASON_STALL = "stall"

TERMINATION_REASON_AWAITING_USER_DECISION = "awaiting_user_decision"


NO_PROGRESS_FAILURE_THRESHOLD = 2
TOOL_OUTPUT_FRAME_THRESHOLD_CHARS = 8192


TERMINATION_REASON_VALUES: frozenset[str] = frozenset(
    {
        TERMINATION_REASON_TASK_COMPLETE,
        TERMINATION_REASON_TOOL_FINAL,
        TERMINATION_REASON_TOOL_DIRECT,
        TERMINATION_REASON_PASSED_GATE,
        TERMINATION_REASON_CONDITION_MET,
        TERMINATION_REASON_TOOL_LOOP_MAX_STEPS,
        TERMINATION_REASON_ITERATION_CAP,
        TERMINATION_REASON_BUDGET_EXHAUSTED_WITH_PARTIAL_RESULT,
        TERMINATION_REASON_CONTEXT_EXHAUSTED,
        TERMINATION_REASON_TIMEOUT,
        TERMINATION_REASON_TIME_BUDGET_EXCEEDED,
        TERMINATION_REASON_CAPABILITY_TOOL_UNAVAILABLE,
        TERMINATION_REASON_FORCED_TOOL_UNAVAILABLE,
        TERMINATION_REASON_BLOCKED_CAP,
        TERMINATION_REASON_BLOCKED_NOVEL_FAILURE,
        TERMINATION_REASON_TOOL_NO_SUCCESS,
        TERMINATION_REASON_MODEL_FINAL,
        TERMINATION_REASON_TOOL_UNAVAILABLE_FINAL,
        TERMINATION_REASON_DUPLICATE_TOOL_CALLS,
        TERMINATION_REASON_FINALIZATION_CONTRACT_MISSING,
        TERMINATION_REASON_EMPTY_PROVIDER_RESPONSE,
        TERMINATION_REASON_REPEATED_FAILURE_STALLED,
        TERMINATION_REASON_LOOP_NO_PROGRESS,
        TERMINATION_REASON_TOOL_ARG_EXHAUSTED,
        TERMINATION_REASON_STALL,
        TERMINATION_REASON_AWAITING_USER_DECISION,
    }
)


SERVICES_TRACES_SUBDIR = "traces"
DEFAULT_TOOL_LOOP_CONTINUE_PROMPT = TOOL_LOOP_CONTINUE_PROMPT
PRIOR_TURN_CONTEXT_CHAR_LIMIT = 300

IDENTITY_RUNTIME_STATUS_NOT_STARTED = "not_started"
IDENTITY_RUNTIME_STATUS_IDENTITYCTL_UNAVAILABLE = "identityctl_unavailable"
IDENTITY_RUNTIME_STATUS_IDENTITY_ROOT_MISSING = "identity_root_missing"
IDENTITY_RUNTIME_STATUS_IDENTITY_ROOT_NOT_DIRECTORY = "identity_root_not_directory"
IDENTITY_RUNTIME_STATUS_NO_YAML_PROFILES = "no_yaml_profiles"
IDENTITY_RUNTIME_STATUS_PARTIAL_FAILURE = "partial_failure"
IDENTITY_RUNTIME_STATUS_SYNC_FAILED = "sync_failed"
IDENTITY_RUNTIME_STATUS_SYNCED = "synced"
IDENTITY_RUNTIME_STATUS_BUNDLE_ROOT_UNSET = "bundle_root_unset"
IDENTITY_RUNTIME_STATUS_BUNDLE_INVALID = "bundle_invalid"
IDENTITY_RUNTIME_STATUS_SKIPPED_AUTHORITY = "skipped_authority"
IDENTITY_RUNTIME_STATUS_SKIPPED_UNCHANGED = "skipped_unchanged"
IDENTITY_RUNTIME_STATUS_BUNDLE_EMPTY = "bundle_empty"
IDENTITY_RUNTIME_STATUS_IMPORTED = "imported"
IDENTITY_RUNTIME_STATUS_IMPORT_FAILED = "import_failed"

__all__ = [
    "DEFAULT_TOOL_LOOP_CONTINUE_PROMPT",
    "PRIOR_TURN_CONTEXT_CHAR_LIMIT",
    "SERVICES_TRACES_SUBDIR",
    "NO_PROGRESS_FAILURE_THRESHOLD",
    "TOOL_OUTPUT_FRAME_THRESHOLD_CHARS",
    "TERMINATION_REASON_VALUES",
    "TERMINATION_REASON_TASK_COMPLETE",
    "TERMINATION_REASON_TOOL_FINAL",
    "TERMINATION_REASON_TOOL_DIRECT",
    "TERMINATION_REASON_PASSED_GATE",
    "TERMINATION_REASON_CONDITION_MET",
    "TERMINATION_REASON_TOOL_LOOP_MAX_STEPS",
    "TERMINATION_REASON_ITERATION_CAP",
    "TERMINATION_REASON_BUDGET_EXHAUSTED_WITH_PARTIAL_RESULT",
    "TERMINATION_REASON_CONTEXT_EXHAUSTED",
    "TERMINATION_REASON_TIMEOUT",
    "TERMINATION_REASON_TIME_BUDGET_EXCEEDED",
    "TERMINATION_REASON_CAPABILITY_TOOL_UNAVAILABLE",
    "TERMINATION_REASON_FORCED_TOOL_UNAVAILABLE",
    "TERMINATION_REASON_BLOCKED_CAP",
    "TERMINATION_REASON_BLOCKED_NOVEL_FAILURE",
    "TERMINATION_REASON_TOOL_NO_SUCCESS",
    "TERMINATION_REASON_MODEL_FINAL",
    "TERMINATION_REASON_TOOL_UNAVAILABLE_FINAL",
    "TERMINATION_REASON_DUPLICATE_TOOL_CALLS",
    "TERMINATION_REASON_FINALIZATION_CONTRACT_MISSING",
    "TERMINATION_REASON_EMPTY_PROVIDER_RESPONSE",
    "TERMINATION_REASON_REPEATED_FAILURE_STALLED",
    "TERMINATION_REASON_LOOP_NO_PROGRESS",
    "TERMINATION_REASON_TOOL_ARG_EXHAUSTED",
    "TERMINATION_REASON_STALL",
    "TERMINATION_REASON_AWAITING_USER_DECISION",
    "IDENTITY_RUNTIME_STATUS_BUNDLE_EMPTY",
    "IDENTITY_RUNTIME_STATUS_BUNDLE_INVALID",
    "IDENTITY_RUNTIME_STATUS_BUNDLE_ROOT_UNSET",
    "IDENTITY_RUNTIME_STATUS_IDENTITYCTL_UNAVAILABLE",
    "IDENTITY_RUNTIME_STATUS_IDENTITY_ROOT_MISSING",
    "IDENTITY_RUNTIME_STATUS_IDENTITY_ROOT_NOT_DIRECTORY",
    "IDENTITY_RUNTIME_STATUS_IMPORTED",
    "IDENTITY_RUNTIME_STATUS_IMPORT_FAILED",
    "IDENTITY_RUNTIME_STATUS_NOT_STARTED",
    "IDENTITY_RUNTIME_STATUS_NO_YAML_PROFILES",
    "IDENTITY_RUNTIME_STATUS_PARTIAL_FAILURE",
    "IDENTITY_RUNTIME_STATUS_SKIPPED_AUTHORITY",
    "IDENTITY_RUNTIME_STATUS_SKIPPED_UNCHANGED",
    "IDENTITY_RUNTIME_STATUS_SYNCED",
    "IDENTITY_RUNTIME_STATUS_SYNC_FAILED",
]
