"""Public identifiers for commerce tools."""

from openminion.modules.tool import PLUGIN_CONTRACT_VERSION
from openminion.modules.tool.contracts.model_ids import (
    MODEL_COMMERCE_INSPECT,
    MODEL_COMMERCE_PLACE_ORDER,
    MODEL_COMMERCE_PREPARE_ORDER,
    MODEL_COMMERCE_PREPARE_ORDER_ACTION,
    MODEL_COMMERCE_APPLY_ORDER_ACTION,
)

COMMERCE_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION
TOOL_COMMERCE_INSPECT = MODEL_COMMERCE_INSPECT
TOOL_COMMERCE_PREPARE_ORDER = MODEL_COMMERCE_PREPARE_ORDER
TOOL_COMMERCE_PLACE_ORDER = MODEL_COMMERCE_PLACE_ORDER
TOOL_COMMERCE_PREPARE_ORDER_ACTION = MODEL_COMMERCE_PREPARE_ORDER_ACTION
TOOL_COMMERCE_APPLY_ORDER_ACTION = MODEL_COMMERCE_APPLY_ORDER_ACTION
READ_COMMERCE_TOOLS = (TOOL_COMMERCE_INSPECT, TOOL_COMMERCE_PREPARE_ORDER)
WRITE_COMMERCE_TOOLS = (TOOL_COMMERCE_PLACE_ORDER,)
ACTION_COMMERCE_TOOLS = (
    TOOL_COMMERCE_PREPARE_ORDER_ACTION,
    TOOL_COMMERCE_APPLY_ORDER_ACTION,
)
ALL_COMMERCE_TOOLS = (
    *READ_COMMERCE_TOOLS,
    *WRITE_COMMERCE_TOOLS,
    *ACTION_COMMERCE_TOOLS,
)

__all__ = [
    "ALL_COMMERCE_TOOLS",
    "ACTION_COMMERCE_TOOLS",
    "COMMERCE_PLUGIN_INTERFACE_VERSION",
    "READ_COMMERCE_TOOLS",
    "TOOL_COMMERCE_INSPECT",
    "TOOL_COMMERCE_APPLY_ORDER_ACTION",
    "TOOL_COMMERCE_PLACE_ORDER",
    "TOOL_COMMERCE_PREPARE_ORDER",
    "TOOL_COMMERCE_PREPARE_ORDER_ACTION",
    "WRITE_COMMERCE_TOOLS",
]
