"""Public identifiers for commerce tools."""

from openminion.modules.tool import PLUGIN_CONTRACT_VERSION
from openminion.modules.tool.contracts.model_ids import (
    MODEL_COMMERCE_INSPECT,
    MODEL_COMMERCE_PREPARE_ORDER,
)

COMMERCE_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION
TOOL_COMMERCE_INSPECT = MODEL_COMMERCE_INSPECT
TOOL_COMMERCE_PREPARE_ORDER = MODEL_COMMERCE_PREPARE_ORDER
ALL_COMMERCE_TOOLS = (TOOL_COMMERCE_INSPECT, TOOL_COMMERCE_PREPARE_ORDER)

__all__ = [
    "ALL_COMMERCE_TOOLS",
    "COMMERCE_PLUGIN_INTERFACE_VERSION",
    "TOOL_COMMERCE_INSPECT",
    "TOOL_COMMERCE_PREPARE_ORDER",
]
