GIT_NOT_AVAILABLE = "GIT_NOT_AVAILABLE"
GIT_NOT_A_REPOSITORY = "GIT_NOT_A_REPOSITORY"
GIT_AMBIGUOUS_WORKSPACE = "GIT_AMBIGUOUS_WORKSPACE"
GIT_DIRTY_WORKING_TREE = "GIT_DIRTY_WORKING_TREE"
GIT_REF_NOT_FOUND = "GIT_REF_NOT_FOUND"
GIT_MERGE_CONFLICT = "GIT_MERGE_CONFLICT"
GIT_DESTRUCTIVE_NOT_APPROVED = "GIT_DESTRUCTIVE_NOT_APPROVED"
GIT_PATH_OUTSIDE_WORKSPACE = "GIT_PATH_OUTSIDE_WORKSPACE"
GIT_BINARY_ERROR = "GIT_BINARY_ERROR"
GIT_NOTHING_TO_COMMIT = "GIT_NOTHING_TO_COMMIT"

ALL_GIT_ERROR_CODES: tuple[str, ...] = (
    GIT_NOT_AVAILABLE,
    GIT_NOT_A_REPOSITORY,
    GIT_AMBIGUOUS_WORKSPACE,
    GIT_DIRTY_WORKING_TREE,
    GIT_REF_NOT_FOUND,
    GIT_MERGE_CONFLICT,
    GIT_DESTRUCTIVE_NOT_APPROVED,
    GIT_PATH_OUTSIDE_WORKSPACE,
    GIT_BINARY_ERROR,
    GIT_NOTHING_TO_COMMIT,
)
