from openminion.modules.tool import PLUGIN_CONTRACT_VERSION

HOST_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION

TOOL_HOST_METRICS = "host.metrics"
TOOL_HOST_INVENTORY_REPORT = "host.inventory_report"

__all__ = [
    "HOST_PLUGIN_INTERFACE_VERSION",
    "TOOL_HOST_INVENTORY_REPORT",
    "TOOL_HOST_METRICS",
]
