from openminion.modules.tool import PLUGIN_CONTRACT_VERSION

HOST_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION

TOOL_HOST_METRICS = "host.metrics"

__all__ = [
    "HOST_PLUGIN_INTERFACE_VERSION",
    "TOOL_HOST_METRICS",
]
