from __future__ import annotations

from openminion.base.version import OPENMINION_VERSION

from .module import AuthRequirement, CommandSchema, CommandSpec, Handler

COMMAND_HELP: dict[str, str] = {
    "help": "Show available commands",
    "status": "Show Telegram/controlplane connection, session, and profile status",
    "new": "Start a fresh session",
    "sessions": "List sessions for this chat/user",
    "session.use": "Rebind this chat to an existing session: /session use <session_id>",
    "session.title": "Set current session title: /session title <text>",
    "export": "Export current session: /export [md|json]",
    "profile": "Show current runtime profile",
    "profile.current": "Show current runtime profile",
    "profile.list": "List configured runtime profiles",
    "profile.ls": "List configured runtime profiles",
    "profile.use": "Switch this session to a runtime profile: /profile use <profile_id>",
    "profile.info": "Show details for a runtime profile: /profile info <profile_id>",
    "profile.stop": "Stop current profile session",
    "agent": "Compatibility alias for /profile",
    "agent.list": "Compatibility alias for /profile list",
    "agent.set": "Compatibility alias for /profile use",
    "agent.ls": "Compatibility alias for /profile list",
    "agent.use": "Compatibility alias for /profile use",
    "agent.info": "Compatibility alias for /profile info",
    "agent.stop": "Compatibility alias for /profile stop",
    "pair": "Show pairing status for this chat",
    "pair.status": "Show pairing status for this chat",
    "pair.revoke": "Revoke pairing for this chat",
    "session.new": "Start a fresh session",
    "session.id": "Show current session ID",
    "session.status": "Show session summary",
    "run": "Show active runs",
    "run.status": "Show run status: /run status <run_id>",
    "cancel": "Cancel run: /cancel <run_id>",
    "job.ls": "List active runs (compatibility alias)",
    "approve": "[admin] Approve policy request: /approve <request_id> [once|10m|1h|forever]",
    "deny": "[admin] Deny policy request: /deny <request_id>",
    "grants": "List active grants",
    "diag": "Show high-level health",
    "logs": "Show run log summary: /logs <run_id>",
    "artifact.ls": "List recent artifacts",
    "memory.ls": "List memory facts",
    "config.show": "Show current config",
    "config.set": "[admin] Set a config value: /config set <key> <value>",
    "artifact.purge": "[admin] Purge deleted artifacts",
    "memory.promote": "[admin] Promote a memory candidate",
    "skill.ingest": "Ingest a SKILL.md file: /skill ingest <path>",
    "skill.list": "List ingested skills",
    "modules": "Show loaded/shadowed/broken module diagnostics",
}

COMMAND_SCOPES: dict[str, tuple[str, ...]] = {
    "help": ("cp.message.read",),
    "status": ("cp.message.read",),
    "new": ("session.write",),
    "sessions": ("session.read",),
    "session.use": ("session.read", "session.write"),
    "session.title": ("session.write",),
    "export": ("session.read",),
    "profile": ("session.read",),
    "profile.current": ("session.read",),
    "profile.list": ("session.read",),
    "profile.ls": ("session.read",),
    "profile.use": ("session.write",),
    "profile.info": ("session.read",),
    "profile.stop": ("session.write",),
    "agent": ("session.read",),
    "agent.list": ("session.read",),
    "agent.set": ("session.write",),
    "agent.ls": ("session.read",),
    "agent.use": ("session.write",),
    "agent.info": ("session.read",),
    "agent.stop": ("session.write",),
    "pair": ("cp.message.read",),
    "pair.status": ("cp.message.read",),
    "pair.revoke": ("session.write",),
    "session.new": ("session.write",),
    "session.id": ("session.read",),
    "session.status": ("session.read",),
    "run": ("session.read",),
    "run.status": ("session.read",),
    "cancel": ("run.cancel",),
    "job.ls": ("session.read",),
    "approve": ("policy.approve",),
    "deny": ("policy.approve",),
    "grants": ("policy.approve",),
    "diag": ("cp.message.read",),
    "logs": ("session.read",),
    "artifact.ls": ("session.read",),
    "artifact.purge": ("session.write",),
    "memory.ls": ("session.read",),
    "memory.promote": ("session.write",),
    "config.show": ("cp.message.read",),
    "config.set": ("session.write",),
    "skill.ingest": ("session.write",),
    "skill.list": ("cp.message.read",),
    "modules": ("cp.message.read",),
}

HELP_HIDDEN_COMMANDS = frozenset(
    {
        "agent",
        "agent.info",
        "agent.list",
        "agent.ls",
        "agent.set",
        "agent.stop",
        "agent.use",
        "job.ls",
        "new",
        "pair.status",
        "profile.current",
        "profile.ls",
    }
)

SCOPE_DESCRIPTIONS: dict[str, str] = {
    "chat.interact": "chat with OpenMinion",
    "cp.message.read": "read controlplane messages",
    "cp.message.write": "send controlplane messages",
    "session.read": "read session state",
    "session.write": "change session state",
    "run.start": "start runs",
    "run.cancel": "cancel runs",
    "policy.approve": "manage policy approvals",
    "tool.weather.read": "use weather tools",
    "tool.search.read": "use search tools",
}

_HANDLER_METHODS: dict[str, str] = {
    "help": "_help",
    "status": "_status",
    "new": "_session_new",
    "sessions": "_sessions",
    "session.use": "_session_use",
    "session.title": "_session_title",
    "export": "_export",
    "profile": "_agent_show",
    "profile.current": "_agent_show",
    "profile.list": "_agent_ls",
    "profile.ls": "_agent_ls",
    "profile.use": "_agent_use",
    "profile.info": "_agent_info",
    "profile.stop": "_agent_stop",
    "agent": "_agent_show",
    "agent.list": "_agent_ls",
    "agent.set": "_agent_use",
    "agent.ls": "_agent_ls",
    "agent.use": "_agent_use",
    "agent.info": "_agent_info",
    "agent.stop": "_agent_stop",
    "pair": "_pair_status",
    "pair.status": "_pair_status",
    "pair.revoke": "_pair_revoke",
    "session.new": "_session_new",
    "session.id": "_session_id",
    "session.status": "_session_status",
    "run": "_run_show",
    "run.status": "_run_status",
    "cancel": "_cancel_run",
    "job.ls": "_job_ls",
    "approve": "_approve",
    "deny": "_deny",
    "grants": "_grants",
    "diag": "_diag",
    "logs": "_logs",
    "artifact.ls": "_artifact_ls",
    "artifact.purge": "_artifact_purge",
    "memory.ls": "_memory_ls",
    "memory.promote": "_memory_promote",
    "config.show": "_config_show",
    "config.set": "_config_set",
    "skill.ingest": "_skill_ingest",
    "skill.list": "_skill_list",
    "modules": "_modules",
}


def builtin_command_specs(registry: object) -> dict[str, CommandSpec]:
    return {
        command_name: _command_spec(command_name, getattr(registry, method_name))
        for command_name, method_name in _HANDLER_METHODS.items()
    }


def _command_spec(command_name: str, handler: Handler) -> CommandSpec:
    help_text = COMMAND_HELP.get(command_name, f"Built-in command: {command_name}")
    schema = CommandSchema(
        name=command_name,
        description=help_text,
        usage=f"/{command_name} [args...]",
    )
    auth_requirement = (
        AuthRequirement.ADMIN if "[admin]" in help_text else AuthRequirement.USER
    )
    return CommandSpec(
        name=command_name,
        schema=schema,
        handler=handler,
        auth_requirement=auth_requirement,
        module_name="builtin",
        version=OPENMINION_VERSION,
        required_scopes=COMMAND_SCOPES[command_name],
    )
