from pathlib import Path

PINCHTAB_URL_ENV = "PINCHTAB_URL"
PINCHTAB_TOKEN_ENV = "PINCHTAB_TOKEN"
PINCHTAB_TOKEN_REF_ENV = "PINCHTAB_TOKEN_REF"
PINCHTAB_TIMEOUT_SECONDS_ENV = "PINCHTAB_TIMEOUT_SECONDS"
PINCHTAB_NAV_TIMEOUT_SECONDS_ENV = "PINCHTAB_NAV_TIMEOUT_SECONDS"
PINCHTAB_ALLOW_REMOTE_ENV = "PINCHTAB_ALLOW_REMOTE"
PINCHTAB_AUTOSTART_ENV = "PINCHTAB_AUTOSTART"
PINCHTAB_LAUNCH_TIMEOUT_SECONDS_ENV = "PINCHTAB_LAUNCH_TIMEOUT_SECONDS"
PINCHTAB_LAUNCH_CMD_ENV = "PINCHTAB_LAUNCH_CMD"
PINCHTAB_LAUNCH_ENV_ENV = "PINCHTAB_LAUNCH_ENV"

DEFAULT_PINCHTAB_BASE_URL = "http://127.0.0.1:9867"
DEFAULT_PINCHTAB_API_TIMEOUT_SECONDS = 20
DEFAULT_PINCHTAB_NAV_TIMEOUT_SECONDS = 30
DEFAULT_PINCHTAB_AUTOSTART_TIMEOUT_SECONDS = 20
DEFAULT_PINCHTAB_OUTPUTS_SUBPATH = Path("browser")
DEFAULT_PINCHTAB_RUNTIME_SUBPATH = Path("tool-runtime") / "pinchtab"

__all__ = [
    "DEFAULT_PINCHTAB_API_TIMEOUT_SECONDS",
    "DEFAULT_PINCHTAB_AUTOSTART_TIMEOUT_SECONDS",
    "DEFAULT_PINCHTAB_BASE_URL",
    "DEFAULT_PINCHTAB_NAV_TIMEOUT_SECONDS",
    "DEFAULT_PINCHTAB_OUTPUTS_SUBPATH",
    "DEFAULT_PINCHTAB_RUNTIME_SUBPATH",
    "PINCHTAB_ALLOW_REMOTE_ENV",
    "PINCHTAB_AUTOSTART_ENV",
    "PINCHTAB_LAUNCH_CMD_ENV",
    "PINCHTAB_LAUNCH_ENV_ENV",
    "PINCHTAB_LAUNCH_TIMEOUT_SECONDS_ENV",
    "PINCHTAB_NAV_TIMEOUT_SECONDS_ENV",
    "PINCHTAB_TIMEOUT_SECONDS_ENV",
    "PINCHTAB_TOKEN_ENV",
    "PINCHTAB_TOKEN_REF_ENV",
    "PINCHTAB_URL_ENV",
]
