WEATHERAPI_PROVIDER_ID = "weatherapi"
WEATHERAPI_DISPLAY_NAME = "WeatherAPI.com"
WEATHERAPI_CURRENT_PATH = "/current.json"

__all__ = [
    "WEATHERAPI_CURRENT_PATH",
    "WEATHERAPI_DISPLAY_NAME",
    "WEATHERAPI_PROVIDER_ID",
]
