from __future__ import annotations

from pathlib import Path

A2A_POLICY_ACTION_ALLOW = "allow"
A2A_POLICY_ACTION_DENY = "deny"
A2A_POLICY_ACTIONS: frozenset[str] = frozenset(
    {A2A_POLICY_ACTION_ALLOW, A2A_POLICY_ACTION_DENY}
)

A2A_IDEMPOTENCY_STATUS_IN_PROGRESS = "IN_PROGRESS"
A2A_IDEMPOTENCY_STATUS_SUCCESS = "SUCCESS"
A2A_IDEMPOTENCY_STATUS_FAILED = "FAILED"
A2A_IDEMPOTENCY_STATUS_CANCELED = "CANCELED"
A2A_IDEMPOTENCY_TERMINAL_STATUSES: frozenset[str] = frozenset(
    {
        A2A_IDEMPOTENCY_STATUS_SUCCESS,
        A2A_IDEMPOTENCY_STATUS_FAILED,
        A2A_IDEMPOTENCY_STATUS_CANCELED,
    }
)

A2A_JOB_STATE_PENDING = "PENDING"
A2A_JOB_STATE_RUNNING = "RUNNING"
A2A_JOB_STATE_SUCCESS = "SUCCESS"
A2A_JOB_STATE_FAILED = "FAILED"
A2A_JOB_STATE_CANCELED = "CANCELED"
A2A_TERMINAL_JOB_STATES: frozenset[str] = frozenset(
    {
        A2A_JOB_STATE_SUCCESS,
        A2A_JOB_STATE_FAILED,
        A2A_JOB_STATE_CANCELED,
    }
)
A2A_ACTIVE_JOB_STATES: tuple[str, ...] = (
    A2A_JOB_STATE_PENDING,
    A2A_JOB_STATE_RUNNING,
)

A2A_AUDIT_STATUS_CALL_RECEIVED = "CALL_RECEIVED"
A2A_AUDIT_STATUS_JOB_QUEUED = "JOB_QUEUED"
A2A_AUDIT_STATUS_RUNNING = "RUNNING"
A2A_AUDIT_STATUS_SUCCESS = "SUCCESS"
A2A_AUDIT_STATUS_FAILED = "FAILED"
A2A_AUDIT_STATUS_CANCELED = "CANCELED"
A2A_AUDIT_STATUS_RECOVERY_FAILED = "RECOVERY_FAILED"

A2A_AGENT_STATUS_ONLINE = "online"

DEFAULT_CONFIG_FILENAME = "a2a.yaml"
DEFAULT_STATE_FILENAME = "state.db"
DEFAULT_AUDIT_DIRNAME = "audit"
DEFAULT_ARTIFACTS_DIRNAME = "artifacts"
DEFAULT_STANDALONE_ROOT_SUBPATH = Path(".a2actl")
DEFAULT_STANDALONE_STATE_SUBPATH = (
    DEFAULT_STANDALONE_ROOT_SUBPATH / DEFAULT_STATE_FILENAME
)
DEFAULT_STANDALONE_AUDIT_SUBPATH = (
    DEFAULT_STANDALONE_ROOT_SUBPATH / DEFAULT_AUDIT_DIRNAME
)
DEFAULT_STANDALONE_ARTIFACT_SUBPATH = (
    DEFAULT_STANDALONE_ROOT_SUBPATH / DEFAULT_ARTIFACTS_DIRNAME
)
DEFAULT_INTEGRATED_ROOT_SUBPATH = Path("a2a")
