FILE_DEFAULT_MAX_ENTRIES = 200
FILE_MAX_ENTRIES = 2000
FILE_DEFAULT_MAX_READ_CHARS = 12000
FILE_MAX_READ_CHARS = 200000
FILE_MAX_WRITE_CHARS = 200000
FILE_SEARCH_MAX_READ_BYTES = 200000
FILE_SEARCH_MAX_SCANNED_FILES = 5000
FILE_BACKEND_LOCAL = "local"
FILE_BACKEND_MEMORY = "memory"

__all__ = [
    "FILE_BACKEND_LOCAL",
    "FILE_BACKEND_MEMORY",
    "FILE_DEFAULT_MAX_ENTRIES",
    "FILE_DEFAULT_MAX_READ_CHARS",
    "FILE_MAX_ENTRIES",
    "FILE_MAX_READ_CHARS",
    "FILE_SEARCH_MAX_SCANNED_FILES",
    "FILE_SEARCH_MAX_READ_BYTES",
    "FILE_MAX_WRITE_CHARS",
]
