from openminion.modules.tool import PLUGIN_CONTRACT_VERSION

IAC_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION
TOOL_IAC_VALIDATE = "iac.validate"
TOOL_IAC_PLAN_CREATE = "iac.plan.create"
TOOL_IAC_PLAN_SHOW = "iac.plan.show"
TOOL_IAC_PROVIDER_FACTS = "iac.provider.facts"

ALL_IAC_TOOLS = (
    TOOL_IAC_VALIDATE,
    TOOL_IAC_PLAN_CREATE,
    TOOL_IAC_PLAN_SHOW,
    TOOL_IAC_PROVIDER_FACTS,
)
