SELF_COMPACTION_EVENT_TYPE = "context.self_compaction"
SELF_COMPACTION_MAX_CHARS = 800

PROVIDER_RETRYABLE_CATEGORIES: frozenset[str] = frozenset(
    {"RATE_LIMITED", "TIMEOUT", "PROVIDER_ERROR"}
)
PROVIDER_RETRY_DEFAULT_MAX_ATTEMPTS = 3
PROVIDER_RETRY_DEFAULT_BASE_BACKOFF_MS = 250.0
PROVIDER_RETRY_DEFAULT_MAX_BACKOFF_MS = 4000.0
PROVIDER_RETRY_DEFAULT_JITTER_RATIO = 0.25
