FIRECRAWL_SEARCH_PROVIDER_ID = "firecrawl"
FIRECRAWL_SEARCH_DISPLAY_NAME = "Firecrawl Search"
FIRECRAWL_SEARCH_API_PATH = "/v2/search"

__all__ = [
    "FIRECRAWL_SEARCH_API_PATH",
    "FIRECRAWL_SEARCH_DISPLAY_NAME",
    "FIRECRAWL_SEARCH_PROVIDER_ID",
]
