from pathlib import Path

from openminion.base.constants import (
    OPENMINION_DATA_ROOT_ENV,
    OPENMINION_MODULE_STANDALONE_ENV,
)

DEFAULT_CONFIG_FILENAME = "skill.yaml"
DEFAULT_SQLITE_FILENAME = "skills.db"

SKILL_STATUS_DRAFT = "draft"
SKILL_STATUS_VERIFIED = "verified"
SKILL_STATUS_BLESSED = "blessed"
SKILL_STATUS_DEPRECATED = "deprecated"
SKILL_STATUS_CHOICES: tuple[str, ...] = (
    SKILL_STATUS_DRAFT,
    SKILL_STATUS_VERIFIED,
    SKILL_STATUS_BLESSED,
    SKILL_STATUS_DEPRECATED,
)
SKILL_STATUSES: frozenset[str] = frozenset(SKILL_STATUS_CHOICES)
SKILL_SOURCE_OPERATOR_DECLARED = "operator_declared"
SKILL_SOURCE_EMERGED_FROM_OBSERVATION = "emerged_from_observation"
SKILL_SOURCE_CHOICES: tuple[str, ...] = (
    SKILL_SOURCE_OPERATOR_DECLARED,
    SKILL_SOURCE_EMERGED_FROM_OBSERVATION,
)
SKILL_SOURCES: frozenset[str] = frozenset(SKILL_SOURCE_CHOICES)
DEFAULT_STATUS_FILTER: tuple[str, ...] = (
    SKILL_STATUS_DRAFT,
    SKILL_STATUS_VERIFIED,
    SKILL_STATUS_BLESSED,
)
HIGH_RISK_STATUS_FILTER: tuple[str, ...] = (
    SKILL_STATUS_BLESSED,
    SKILL_STATUS_VERIFIED,
)

RISK_CLASS_LOW = "low"
RISK_CLASS_MEDIUM = "medium"
RISK_CLASS_HIGH = "high"
RISK_CLASS_CHOICES: tuple[str, ...] = (
    RISK_CLASS_LOW,
    RISK_CLASS_MEDIUM,
    RISK_CLASS_HIGH,
)
RISK_CLASSES: frozenset[str] = frozenset(RISK_CLASS_CHOICES)
HIGH_RISK_CLASSES: frozenset[str] = frozenset({RISK_CLASS_MEDIUM, RISK_CLASS_HIGH})
VERIFIED_SKILL_STATUSES: frozenset[str] = frozenset(
    {SKILL_STATUS_VERIFIED, SKILL_STATUS_BLESSED}
)

SKILL_TOOL_REGISTRY_UNAVAILABLE = "unavailable"
SKILL_TOOL_REGISTRY_AVAILABLE_EMPTY = "available_empty"
SKILL_TOOL_REGISTRY_AVAILABLE = "available"
SKILL_TOOL_REGISTRY_STATES: frozenset[str] = frozenset(
    {
        SKILL_TOOL_REGISTRY_UNAVAILABLE,
        SKILL_TOOL_REGISTRY_AVAILABLE_EMPTY,
        SKILL_TOOL_REGISTRY_AVAILABLE,
    }
)

SKILL_MATCH_EXACT_ID_SCORE = 24.0
SKILL_MATCH_EXACT_NAME_SCORE = 20.0
SKILL_MATCH_EXACT_PHRASE_SCORE = 10.0
SKILL_MATCH_IDENTITY_TOKEN_SCORE = 4.0
SKILL_MATCH_IDENTITY_TOKEN_CAP = 12.0
SKILL_MATCH_COMPACT_TOKEN_SCORE = 2.0
SKILL_MATCH_COMPACT_TOKEN_CAP = 10.0
SKILL_MATCH_PROCEDURE_TOKEN_SCORE = 1.0
SKILL_MATCH_PROCEDURE_TOKEN_CAP = 6.0

DEFAULT_STANDALONE_ROOT_SUBPATH = Path(".skill")
DEFAULT_INTEGRATED_ROOT_SUBPATH = Path("skill")
DEFAULT_STANDALONE_SQLITE_SUBPATH = (
    DEFAULT_STANDALONE_ROOT_SUBPATH / DEFAULT_SQLITE_FILENAME
)
DEFAULT_INTEGRATED_SQLITE_SUBPATH = (
    DEFAULT_INTEGRATED_ROOT_SUBPATH / DEFAULT_SQLITE_FILENAME
)

__all__ = (
    "DEFAULT_CONFIG_FILENAME",
    "DEFAULT_INTEGRATED_ROOT_SUBPATH",
    "DEFAULT_INTEGRATED_SQLITE_SUBPATH",
    "DEFAULT_SQLITE_FILENAME",
    "DEFAULT_STANDALONE_ROOT_SUBPATH",
    "DEFAULT_STANDALONE_SQLITE_SUBPATH",
    "DEFAULT_STATUS_FILTER",
    "HIGH_RISK_CLASSES",
    "HIGH_RISK_STATUS_FILTER",
    "OPENMINION_DATA_ROOT_ENV",
    "OPENMINION_MODULE_STANDALONE_ENV",
    "RISK_CLASS_CHOICES",
    "RISK_CLASS_HIGH",
    "RISK_CLASS_LOW",
    "RISK_CLASS_MEDIUM",
    "RISK_CLASSES",
    "SKILL_STATUSES",
    "SKILL_STATUS_BLESSED",
    "SKILL_STATUS_CHOICES",
    "SKILL_STATUS_DEPRECATED",
    "SKILL_STATUS_DRAFT",
    "SKILL_STATUS_VERIFIED",
    "SKILL_TOOL_REGISTRY_AVAILABLE",
    "SKILL_TOOL_REGISTRY_AVAILABLE_EMPTY",
    "SKILL_TOOL_REGISTRY_STATES",
    "SKILL_TOOL_REGISTRY_UNAVAILABLE",
    "SKILL_MATCH_COMPACT_TOKEN_CAP",
    "SKILL_MATCH_COMPACT_TOKEN_SCORE",
    "SKILL_MATCH_EXACT_ID_SCORE",
    "SKILL_MATCH_EXACT_NAME_SCORE",
    "SKILL_MATCH_EXACT_PHRASE_SCORE",
    "SKILL_MATCH_IDENTITY_TOKEN_CAP",
    "SKILL_MATCH_IDENTITY_TOKEN_SCORE",
    "SKILL_MATCH_PROCEDURE_TOKEN_CAP",
    "SKILL_MATCH_PROCEDURE_TOKEN_SCORE",
    "SKILL_SOURCE_CHOICES",
    "SKILL_SOURCE_EMERGED_FROM_OBSERVATION",
    "SKILL_SOURCE_OPERATOR_DECLARED",
    "SKILL_SOURCES",
    "VERIFIED_SKILL_STATUSES",
)
