DUCKDUCKGO_SEARCH_PROVIDER_ID = "duckduckgo"
DUCKDUCKGO_SEARCH_DISPLAY_NAME = "DuckDuckGo Search"
DEFAULT_DUCKDUCKGO_SEARCH_URL = "https://html.duckduckgo.com/html/"
DEFAULT_DUCKDUCKGO_SEARCH_TIMEOUT_SECONDS = 20.0

__all__ = [
    "DEFAULT_DUCKDUCKGO_SEARCH_TIMEOUT_SECONDS",
    "DEFAULT_DUCKDUCKGO_SEARCH_URL",
    "DUCKDUCKGO_SEARCH_DISPLAY_NAME",
    "DUCKDUCKGO_SEARCH_PROVIDER_ID",
]
