from openminion.modules.brain.loop.tools import (
    ADAPTIVE_TERM_BUDGET_EXHAUSTED,
    ADAPTIVE_TERM_CONFIDENT_COMPLETE,
    ADAPTIVE_TERM_DISALLOWED_TOOL,
    ADAPTIVE_TERM_FINAL_TEXT,
    ADAPTIVE_TERM_ITERATION_CAP,
    ADAPTIVE_TERM_JOB_PENDING,
    ADAPTIVE_TERM_LLM_ERROR,
    ADAPTIVE_TERM_NEEDS_USER,
    AdaptiveToolLoopLLMRuntime,
)
from openminion.modules.brain.loop.strategies.coding.constants import (
    CODING_TERM_VERIFY_CAP_EXCEEDED as CODING_TERM_VERIFY_CAP_EXCEEDED,
)
from openminion.modules.tool.contracts.model_ids import (
    MODEL_CODE_GREP,
    MODEL_CODE_PATCH,
    MODEL_CODE_REPO_INDEX,
    MODEL_CODE_REPO_MAP,
    MODEL_CODE_SYMBOL_FIND,
    MODEL_EXEC_KILL,
    MODEL_EXEC_LIST,
    MODEL_EXEC_POLL,
    MODEL_EXEC_RUN,
    MODEL_TASK_DELEGATE,
    MODEL_FILE_FIND,
    MODEL_FILE_LIST_DIR,
    MODEL_FILE_READ,
    MODEL_FILE_READ_RANGE,
    MODEL_FILE_WRITE,
    MODEL_WEB_FETCH,
)

CODING_ALLOWED_TOOLS: frozenset[str] = frozenset(
    (
        MODEL_FILE_LIST_DIR,
        MODEL_FILE_READ,
        MODEL_FILE_READ_RANGE,
        MODEL_FILE_FIND,
        MODEL_FILE_WRITE,
        MODEL_CODE_PATCH,
        MODEL_CODE_GREP,
        MODEL_CODE_REPO_MAP,
        MODEL_CODE_REPO_INDEX,
        MODEL_CODE_SYMBOL_FIND,
        MODEL_WEB_FETCH,
        MODEL_EXEC_RUN,
        MODEL_EXEC_POLL,
        MODEL_EXEC_LIST,
        MODEL_EXEC_KILL,
        MODEL_TASK_DELEGATE,
    )
)

CODING_V1_ALLOWED_TOOLS = CODING_ALLOWED_TOOLS

CODING_TERM_FINAL_TEXT = ADAPTIVE_TERM_FINAL_TEXT
CODING_TERM_CONFIDENT_COMPLETE = ADAPTIVE_TERM_CONFIDENT_COMPLETE
CODING_TERM_NEEDS_USER = ADAPTIVE_TERM_NEEDS_USER
CODING_TERM_JOB_PENDING = ADAPTIVE_TERM_JOB_PENDING
CODING_TERM_BUDGET_EXHAUSTED = ADAPTIVE_TERM_BUDGET_EXHAUSTED
CODING_TERM_DISALLOWED_TOOL = ADAPTIVE_TERM_DISALLOWED_TOOL
CODING_TERM_LLM_ERROR = ADAPTIVE_TERM_LLM_ERROR
CODING_TERM_TOOL_FAILURE = "tool_failure"
CODING_TERM_ITERATION_CAP = ADAPTIVE_TERM_ITERATION_CAP


class CodingModeError(Exception):
    pass


class CodingRuntimeUnavailableError(CodingModeError):
    pass


CodingLLMRuntime = AdaptiveToolLoopLLMRuntime
