OPENMINION_WEB_SEARCH_PROVIDER_ENV = "OPENMINION_WEB_SEARCH_PROVIDER"
OPENMINION_POLICY_PATH_ENV = "OPENMINION_POLICY_PATH"

MEMORY_SEARCH_MODEL_CHUNK_SIZE = 1000
MEMORY_SEARCH_MODEL_MAX_CHUNKS = 8

TOOL_REASON_STORAGE_UNCONFIGURED = "storage_unconfigured"
TOOL_REASON_STORAGE_UNAVAILABLE = "storage_unavailable"
TOOL_REASON_STORAGE_EXEC_ERROR = "storage_exec_error"
TOOL_REASON_RECORD_NOT_FOUND = "record_not_found"

__all__ = [
    "MEMORY_SEARCH_MODEL_CHUNK_SIZE",
    "MEMORY_SEARCH_MODEL_MAX_CHUNKS",
    "OPENMINION_POLICY_PATH_ENV",
    "OPENMINION_WEB_SEARCH_PROVIDER_ENV",
    "TOOL_REASON_RECORD_NOT_FOUND",
    "TOOL_REASON_STORAGE_EXEC_ERROR",
    "TOOL_REASON_STORAGE_UNAVAILABLE",
    "TOOL_REASON_STORAGE_UNCONFIGURED",
]
