SERPER_SEARCH_PROVIDER_ID = "serper"
SERPER_SEARCH_DISPLAY_NAME = "Serper Search"
SERPER_API_URL_ENV = "SERPER_API_URL"
SERPER_TIMEOUT_SECONDS_ENV = "SERPER_TIMEOUT_SECONDS"
DEFAULT_SERPER_API_URL = "https://google.serper.dev/search"
DEFAULT_SERPER_TIMEOUT_SECONDS = 20.0

__all__ = [
    "DEFAULT_SERPER_API_URL",
    "DEFAULT_SERPER_TIMEOUT_SECONDS",
    "SERPER_API_URL_ENV",
    "SERPER_SEARCH_DISPLAY_NAME",
    "SERPER_SEARCH_PROVIDER_ID",
    "SERPER_TIMEOUT_SECONDS_ENV",
]
