STATUS_TODO = "todo"
STATUS_IN_PROGRESS = "in_progress"
STATUS_DONE = "done"
STATUS_BLOCKED = "blocked"

VALID_STATUSES: tuple[str, ...] = (
    STATUS_TODO,
    STATUS_IN_PROGRESS,
    STATUS_DONE,
    STATUS_BLOCKED,
)

DEFAULT_MAX_SESSIONS = 100
DEFAULT_MAX_ITEMS_PER_PLAN = 100
