# ruff: noqa: F403,F405
from .common import *
from .common import _StrictTaskModel

class PlanStepDraft(_StrictTaskModel):
    """Authoring-time step definition."""

    step_id: str | None = None
    title: str = Field(min_length=1)
    instruction: str = Field(min_length=1)

class PlanDraft(_StrictTaskModel):
    """Structured plan generated by brain PLAN mode."""

    plan_id: str | None = None
    plan_name: str | None = None
    root_goal_id: str | None = None
    steps: list[PlanStepDraft] = Field(min_length=1)
    assumptions: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)

class PlanStepRecord(_StrictTaskModel):
    """Durable step row attached to a task plan."""

    step_id: str
    order_index: int = Field(ge=1)
    title: str
    instruction: str
    status: PlanStepStatus = PlanStepStatus.PENDING
    note: str | None = None
    artifact_refs: list[str] = Field(default_factory=list)
    executing_mode: str | None = None
    updated_at: datetime

class PlanRecord(_StrictTaskModel):
    """Durable plan row attached to a task."""

    plan_id: str
    task_id: str
    plan_name: str | None = None
    root_goal_id: str | None = None
    created_by_mode: str | None = None
    steps: list[PlanStepRecord]
    created_at: datetime
    updated_at: datetime

class StepUpdateInput(_StrictTaskModel):
    """Step transition payload from runtime EXECUTE mode."""

    status: PlanStepStatus
    note: str | None = None
    artifact_refs: list[str] = Field(default_factory=list)
    idempotency_key: str | None = None
    executing_mode: str | None = None
