from pathlib import Path

from openminion.modules.paths import MEMORY_DB_SUBPATH

MEMCTL_CONFIG_ENV = "MEMCTL_CONFIG"
OPENMINION_MEMORY_TRACE_ENV = "OPENMINION_MEMORY_TRACE"
OPENMINION_MEMORY_TRACE_FILE_ENV = "OPENMINION_MEMORY_TRACE_FILE"

NORMALIZED_KEY_MAX_LENGTH = 128

MEMORY_CANDIDATE_STATUS_PROPOSED = "proposed"
MEMORY_CANDIDATE_STATUS_APPROVED = "approved"
MEMORY_CANDIDATE_STATUS_REJECTED = "rejected"
MEMORY_CANDIDATE_STATUS_PROMOTED = "promoted"
MEMORY_CANDIDATE_STATUS_CHOICES: tuple[str, ...] = (
    MEMORY_CANDIDATE_STATUS_PROPOSED,
    MEMORY_CANDIDATE_STATUS_APPROVED,
    MEMORY_CANDIDATE_STATUS_REJECTED,
    MEMORY_CANDIDATE_STATUS_PROMOTED,
)
PROMOTABLE_MEMORY_CANDIDATE_STATUSES: frozenset[str] = frozenset(
    {
        MEMORY_CANDIDATE_STATUS_PROPOSED,
        MEMORY_CANDIDATE_STATUS_APPROVED,
    }
)

DEFAULT_CONFIDENCE: dict[str, float] = {
    "user_said": 0.8,
    "tool_output": 0.9,
    "agent_inferred": 0.5,
    "validated": 0.95,
    "imported": 0.85,
}

MEMORY_CONSOLIDATION_CONTENT_PREVIEW_MAX_CHARS = 220
MEMORY_GC_SUMMARY_COMPRESS_AFTER_DAYS = 30
MEMORY_GC_SUMMARY_DELETE_AFTER_DAYS = 90
MEMORY_GC_SUMMARY_COMPRESS_MAX_CHARS = 100

DEFAULT_CONFIG_FILENAME = "memory.yaml"
DEFAULT_STANDALONE_ROOT_SUBPATH = Path(".memctl")
DEFAULT_STANDALONE_SQLITE_SUBPATH = DEFAULT_STANDALONE_ROOT_SUBPATH / "memory.db"
DEFAULT_INTEGRATED_SQLITE_SUBPATH = MEMORY_DB_SUBPATH
DEFAULT_TRACE_FILENAME = "memory_trace.jsonl"
