from datetime import datetime
from enum import StrEnum
from typing import Annotated, Literal
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field


class _StrictTaskModel(BaseModel):
    model_config = ConfigDict(extra="forbid")


class TaskStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    WAITING = "WAITING"
    DONE = "DONE"
    CANCELED = "CANCELED"


class PlanStepStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    DONE = "DONE"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class TaskCreateInput(_StrictTaskModel):
    """Payload for creating a durable task."""

    task_id: str | None = None
    title: str = Field(min_length=1)
    description: str | None = None
    due_at: datetime | None = None
    scheduled_at: datetime | None = None
    wait_at: datetime | None = None
    labels: list[str] = Field(default_factory=list)
    created_by_mode: str | None = None


class TaskRecord(_StrictTaskModel):
    """Canonical task entity persisted by the task module."""

    task_id: str
    title: str
    description: str | None = None
    status: TaskStatus = TaskStatus.PENDING
    due_at: datetime | None = None
    scheduled_at: datetime | None = None
    wait_at: datetime | None = None
    labels: list[str] = Field(default_factory=list)
    created_by_mode: str | None = None
    executing_mode: str | None = None
    current_plan_id: str | None = None
    next_step_id: str | None = None
    created_at: datetime
    updated_at: datetime


class PlanStepDraft(_StrictTaskModel):
    """Authoring-time step definition."""

    step_id: str | None = None
    title: str = Field(min_length=1)
    instruction: str = Field(min_length=1)


class PlanDraft(_StrictTaskModel):
    """Structured plan generated by brain PLAN mode."""

    plan_id: str | None = None
    plan_name: str | None = None
    root_goal_id: str | None = None
    steps: list[PlanStepDraft] = Field(min_length=1)
    assumptions: list[str] = Field(default_factory=list)
    risks: list[str] = Field(default_factory=list)


class PlanStepRecord(_StrictTaskModel):
    """Durable step row attached to a task plan."""

    step_id: str
    order_index: int = Field(ge=1)
    title: str
    instruction: str
    status: PlanStepStatus = PlanStepStatus.PENDING
    note: str | None = None
    artifact_refs: list[str] = Field(default_factory=list)
    executing_mode: str | None = None
    updated_at: datetime


class PlanRecord(_StrictTaskModel):
    """Durable plan row attached to a task."""

    plan_id: str
    task_id: str
    plan_name: str | None = None
    root_goal_id: str | None = None
    created_by_mode: str | None = None
    steps: list[PlanStepRecord]
    created_at: datetime
    updated_at: datetime


class StepUpdateInput(_StrictTaskModel):
    """Step transition payload from runtime EXECUTE mode."""

    status: PlanStepStatus
    note: str | None = None
    artifact_refs: list[str] = Field(default_factory=list)
    idempotency_key: str | None = None
    executing_mode: str | None = None


class ResumePointer(_StrictTaskModel):
    """Stable cursor for pausing and resuming execution exactly once."""

    task_id: str
    plan_id: str
    step_id: str
    attempt: int = Field(default=1, ge=1)
    trace_id: str
    turn_id: str | None = None
    pack_id: str | None = None


class PendingAction(_StrictTaskModel):
    """Approval checkpoint returned by runtime when policy blocks execution."""

    pending_action_id: str = Field(default_factory=lambda: f"pa_{uuid4().hex[:10]}")
    policy_request_id: str
    state: Literal["NEEDS_APPROVAL"] = "NEEDS_APPROVAL"
    reason: str | None = None
    cursor: ResumePointer
    created_at: datetime
    resolved_at: datetime | None = None
    decision_id: str | None = None


class DecisionDigest(_StrictTaskModel):
    """Short execution summary suitable for prompt injection."""

    mode: Literal["PLAN", "EXECUTE"]
    current_task_id: str | None = None
    current_step_id: str | None = None
    summary: str


class TaskDigestTask(_StrictTaskModel):
    """Compact task line for context packs."""

    task_id: str
    title: str
    status: TaskStatus
    next_step_id: str | None = None
    next_step_title: str | None = None
    due_at: datetime | None = None


class TaskDigest(_StrictTaskModel):
    """Bounded task snapshot used by openminion-context."""

    agent_id: str
    session_id: str
    generated_at: datetime
    tasks_ready: list[TaskDigestTask] = Field(default_factory=list)
    tasks_active: list[TaskDigestTask] = Field(default_factory=list)
    current_task: TaskDigestTask | None = None
    blockers: list[str] = Field(default_factory=list)
    max_items: int = Field(default=5, ge=1)


class TaskEvent(_StrictTaskModel):
    """Task event contract."""

    type: str
    at: datetime
    task_id: str | None = None
    plan_id: str | None = None
    step_id: str | None = None
    trace_id: str | None = None
    payload: dict[str, object] = Field(default_factory=dict)


class TaskCreateOp(_StrictTaskModel):
    op: Literal["task.create"] = "task.create"
    input: TaskCreateInput


class TaskAttachPlanOp(_StrictTaskModel):
    op: Literal["task.attach_plan"] = "task.attach_plan"
    task_id: str
    plan: PlanDraft


class TaskStepUpdateOp(_StrictTaskModel):
    op: Literal["task.step_update"] = "task.step_update"
    task_id: str
    step_id: str
    input: StepUpdateInput


class TaskStatusTransitionOp(_StrictTaskModel):
    op: Literal["task.status_transition"] = "task.status_transition"
    task_id: str
    status: TaskStatus


TaskOp = Annotated[
    TaskCreateOp | TaskAttachPlanOp | TaskStepUpdateOp | TaskStatusTransitionOp,
    Field(discriminator="op"),
]


class TaskOps(_StrictTaskModel):
    """Batch of durable operations emitted by planner/executor."""

    ops: list[TaskOp] = Field(default_factory=list)
