OPENMINION_IP_PUBLIC_ENDPOINTS_ENV = "OPENMINION_IP_PUBLIC_ENDPOINTS"
OPENMINION_IP_PUBLIC_TIMEOUT_SECONDS_ENV = "OPENMINION_IP_PUBLIC_TIMEOUT_SECONDS"
DEFAULT_IP_PUBLIC_LOOKUP_ENDPOINTS: tuple[str, ...] = (
    "https://api.ipify.org?format=json",
    "https://ifconfig.me/ip",
    "https://icanhazip.com",
)
DEFAULT_IP_PROVIDER_ID = "builtin"

__all__ = [
    "DEFAULT_IP_PROVIDER_ID",
    "DEFAULT_IP_PUBLIC_LOOKUP_ENDPOINTS",
    "OPENMINION_IP_PUBLIC_ENDPOINTS_ENV",
    "OPENMINION_IP_PUBLIC_TIMEOUT_SECONDS_ENV",
]
