from openminion.base.version import OPENMINION_VERSION

MCP_CLIENT_NAME = "openminion"
MCP_CLIENT_VERSION = OPENMINION_VERSION
MCP_COMPLETION_COMPLETE_METHOD = "completion/complete"
MCP_INITIALIZE_METHOD = "initialize"
MCP_INITIALIZED_NOTIFICATION = "notifications/initialized"
MCP_TOOLS_LIST_METHOD = "tools/list"
MCP_TOOLS_CALL_METHOD = "tools/call"
MCP_PROMPTS_LIST_METHOD = "prompts/list"
MCP_PROMPTS_GET_METHOD = "prompts/get"
MCP_RESOURCES_LIST_METHOD = "resources/list"
MCP_RESOURCES_READ_METHOD = "resources/read"
MCP_RESOURCES_SUBSCRIBE_METHOD = "resources/subscribe"
MCP_RESOURCES_TEMPLATES_LIST_METHOD = "resources/templates/list"
MCP_RESOURCES_UNSUBSCRIBE_METHOD = "resources/unsubscribe"
MCP_RESOURCES_UPDATED_NOTIFICATION = "notifications/resources/updated"
MCP_ROOTS_LIST_METHOD = "roots/list"
MCP_SAMPLING_CREATE_MESSAGE_METHOD = "sampling/createMessage"
MCP_ELICITATION_CREATE_METHOD = "elicitation/create"
MCP_ELICITATION_COMPLETE_NOTIFICATION = "notifications/elicitation/complete"
MCP_LOGGING_MESSAGE_NOTIFICATION = "notifications/message"
MCP_LOGGING_SET_LEVEL_METHOD = "logging/setLevel"
MCP_MAX_INPUT_ROUNDS = 10
MCP_MODERN_RESPONSE_CACHE_MAX_ENTRIES = 128
MCP_SERVER_DISCOVER_METHOD = "server/discover"
MCP_SUBSCRIPTIONS_LISTEN_METHOD = "subscriptions/listen"
MCP_TASKS_CANCEL_METHOD = "tasks/cancel"
MCP_TASKS_GET_METHOD = "tasks/get"
MCP_TASKS_UPDATE_METHOD = "tasks/update"

__all__ = [
    "MCP_CLIENT_NAME",
    "MCP_CLIENT_VERSION",
    "MCP_COMPLETION_COMPLETE_METHOD",
    "MCP_INITIALIZE_METHOD",
    "MCP_INITIALIZED_NOTIFICATION",
    "MCP_LOGGING_MESSAGE_NOTIFICATION",
    "MCP_LOGGING_SET_LEVEL_METHOD",
    "MCP_MAX_INPUT_ROUNDS",
    "MCP_MODERN_RESPONSE_CACHE_MAX_ENTRIES",
    "MCP_PROMPTS_GET_METHOD",
    "MCP_PROMPTS_LIST_METHOD",
    "MCP_RESOURCES_LIST_METHOD",
    "MCP_RESOURCES_READ_METHOD",
    "MCP_RESOURCES_SUBSCRIBE_METHOD",
    "MCP_RESOURCES_TEMPLATES_LIST_METHOD",
    "MCP_RESOURCES_UNSUBSCRIBE_METHOD",
    "MCP_RESOURCES_UPDATED_NOTIFICATION",
    "MCP_ROOTS_LIST_METHOD",
    "MCP_SERVER_DISCOVER_METHOD",
    "MCP_SAMPLING_CREATE_MESSAGE_METHOD",
    "MCP_SUBSCRIPTIONS_LISTEN_METHOD",
    "MCP_TASKS_CANCEL_METHOD",
    "MCP_TASKS_GET_METHOD",
    "MCP_TASKS_UPDATE_METHOD",
    "MCP_ELICITATION_CREATE_METHOD",
    "MCP_ELICITATION_COMPLETE_NOTIFICATION",
    "MCP_TOOLS_CALL_METHOD",
    "MCP_TOOLS_LIST_METHOD",
]
