MCP_PROTOCOL_VERSION = "2025-06-18"
MCP_PROTOCOL_VERSION_FLOOR = "2025-03-26"
MCP_MODERN_PROTOCOL_VERSION = "2026-07-28"
MCP_PREVIOUS_PROTOCOL_VERSION = "2025-11-25"
MCP_SUPPORTED_PROTOCOL_VERSIONS = (
    MCP_MODERN_PROTOCOL_VERSION,
    MCP_PREVIOUS_PROTOCOL_VERSION,
    MCP_PROTOCOL_VERSION,
    MCP_PROTOCOL_VERSION_FLOOR,
)


__all__ = [
    "MCP_PROTOCOL_VERSION",
    "MCP_PROTOCOL_VERSION_FLOOR",
    "MCP_MODERN_PROTOCOL_VERSION",
    "MCP_PREVIOUS_PROTOCOL_VERSION",
    "MCP_SUPPORTED_PROTOCOL_VERSIONS",
]
