MCP_PROTOCOL_VERSION = "2025-11-25"
MCP_PROTOCOL_VERSION_FLOOR = "2025-03-26"
MCP_MODERN_PROTOCOL_VERSION = "2026-07-28"
MCP_PREVIOUS_PROTOCOL_VERSION = "2025-06-18"
MCP_HEADER_MISMATCH_ERROR = -32020
MCP_MISSING_CLIENT_CAPABILITY_ERROR = -32021
MCP_UNSUPPORTED_PROTOCOL_VERSION_ERROR = -32022
MCP_MODERN_PROTOCOL_ERROR_CODES = frozenset(
    {
        -32601,
        MCP_HEADER_MISMATCH_ERROR,
        MCP_MISSING_CLIENT_CAPABILITY_ERROR,
        MCP_UNSUPPORTED_PROTOCOL_VERSION_ERROR,
    }
)
MCP_SUPPORTED_PROTOCOL_VERSIONS = (
    MCP_MODERN_PROTOCOL_VERSION,
    MCP_PREVIOUS_PROTOCOL_VERSION,
    MCP_PROTOCOL_VERSION,
    MCP_PROTOCOL_VERSION_FLOOR,
)


__all__ = [
    "MCP_PROTOCOL_VERSION",
    "MCP_PROTOCOL_VERSION_FLOOR",
    "MCP_MODERN_PROTOCOL_VERSION",
    "MCP_MODERN_PROTOCOL_ERROR_CODES",
    "MCP_HEADER_MISMATCH_ERROR",
    "MCP_MISSING_CLIENT_CAPABILITY_ERROR",
    "MCP_PREVIOUS_PROTOCOL_VERSION",
    "MCP_SUPPORTED_PROTOCOL_VERSIONS",
    "MCP_UNSUPPORTED_PROTOCOL_VERSION_ERROR",
]
