"""Policy constants."""

from pathlib import Path

POLICY_MODE_DISABLED = "disabled"
POLICY_MODE_LOG_ONLY = "log_only"
POLICY_MODE_ENFORCE = "enforce"
POLICY_MODE_ENFORCE_SAFE = "enforce_safe"
POLICY_MODE_CHOICES: tuple[str, ...] = (
    POLICY_MODE_DISABLED,
    POLICY_MODE_LOG_ONLY,
    POLICY_MODE_ENFORCE,
    POLICY_MODE_ENFORCE_SAFE,
)
POLICY_MODES: frozenset[str] = frozenset(POLICY_MODE_CHOICES)

POLICY_DECISION_ALLOW = "ALLOW"
POLICY_DECISION_DENY = "DENY"
POLICY_DECISION_REQUIRE_CONFIRM = "REQUIRE_CONFIRM"
POLICY_DECISION_CHOICES: tuple[str, ...] = (
    POLICY_DECISION_ALLOW,
    POLICY_DECISION_DENY,
    POLICY_DECISION_REQUIRE_CONFIRM,
)

POLICY_GRANT_EFFECT_ALLOW = "allow"
POLICY_GRANT_EFFECT_DENY = "deny"
POLICY_GRANT_EFFECT_CHOICES: tuple[str, ...] = (
    POLICY_GRANT_EFFECT_ALLOW,
    POLICY_GRANT_EFFECT_DENY,
)
POLICY_GRANT_EFFECTS: frozenset[str] = frozenset(POLICY_GRANT_EFFECT_CHOICES)

POLICY_DURATION_ONCE = "once"
POLICY_DURATION_UNTIL = "until"
POLICY_DURATION_SESSION = "session"
POLICY_DURATION_FOREVER = "forever"
POLICY_DURATION_CHOICES: tuple[str, ...] = (
    POLICY_DURATION_ONCE,
    POLICY_DURATION_UNTIL,
    POLICY_DURATION_SESSION,
    POLICY_DURATION_FOREVER,
)
POLICY_DURATION_TYPES: frozenset[str] = frozenset(POLICY_DURATION_CHOICES)

POLICY_RISK_READ = "read"
POLICY_RISK_WRITE = "write"
POLICY_RISK_EXEC = "exec"
POLICY_RISK_STATE_CHANGE = "state_change"
POLICY_RISK_DESTRUCTIVE = "destructive"
POLICY_RISK_FINANCIAL = "financial"
POLICY_RISK_SECURITY = "security"
POLICY_RISK_CHOICES: tuple[str, ...] = (
    POLICY_RISK_READ,
    POLICY_RISK_WRITE,
    POLICY_RISK_EXEC,
    POLICY_RISK_STATE_CHANGE,
    POLICY_RISK_DESTRUCTIVE,
    POLICY_RISK_FINANCIAL,
    POLICY_RISK_SECURITY,
)
POLICY_HIGH_CONFIRM_RISKS: frozenset[str] = frozenset(
    (
        POLICY_RISK_DESTRUCTIVE,
        POLICY_RISK_FINANCIAL,
        POLICY_RISK_SECURITY,
    )
)
POLICY_SIDE_EFFECT_CONFIRM_RISKS: frozenset[str] = frozenset(
    (
        POLICY_RISK_EXEC,
        POLICY_RISK_STATE_CHANGE,
    )
)

POLICY_SIDE_EFFECT_NONE = "none"
POLICY_SIDE_EFFECT_LOCAL = "local"
POLICY_SIDE_EFFECT_REMOTE = "remote"
POLICY_SIDE_EFFECT_EXTERNAL_ACCOUNT = "external_account"
POLICY_SIDE_EFFECT_CHOICES: tuple[str, ...] = (
    POLICY_SIDE_EFFECT_NONE,
    POLICY_SIDE_EFFECT_LOCAL,
    POLICY_SIDE_EFFECT_REMOTE,
    POLICY_SIDE_EFFECT_EXTERNAL_ACCOUNT,
)
POLICY_SIDE_EFFECTS: frozenset[str] = frozenset(POLICY_SIDE_EFFECT_CHOICES)

POLICY_REVERSIBILITY_REVERSIBLE = "reversible"
POLICY_REVERSIBILITY_PARTIALLY_REVERSIBLE = "partially_reversible"
POLICY_REVERSIBILITY_IRREVERSIBLE = "irreversible"
POLICY_REVERSIBILITY_UNKNOWN = "unknown"
POLICY_REVERSIBILITY_CHOICES: tuple[str, ...] = (
    POLICY_REVERSIBILITY_REVERSIBLE,
    POLICY_REVERSIBILITY_PARTIALLY_REVERSIBLE,
    POLICY_REVERSIBILITY_IRREVERSIBLE,
    POLICY_REVERSIBILITY_UNKNOWN,
)
POLICY_REVERSIBILITY_VALUES: frozenset[str] = frozenset(POLICY_REVERSIBILITY_CHOICES)

POLICY_CONFIRM_RESPONSE_AFFIRM = "affirm"
POLICY_CONFIRM_RESPONSE_DENY = "deny"
POLICY_CONFIRM_RESPONSE_UNCLEAR = "unclear"
POLICY_CONFIRM_RESPONSE_CHOICES: tuple[str, ...] = (
    POLICY_CONFIRM_RESPONSE_AFFIRM,
    POLICY_CONFIRM_RESPONSE_DENY,
    POLICY_CONFIRM_RESPONSE_UNCLEAR,
)

POLICY_SUBJECT_ID_LOCAL = "local"

DEFAULT_STANDALONE_SQLITE_SUBPATH = Path(".openminion") / "policy" / "policy.db"
DEFAULT_INTEGRATED_SQLITE_SUBPATH = Path("policy") / "policy.db"
