from enum import Enum


class ReasonCode(str, Enum):
    """Stable audit reason codes for ``MetaResult.reasons``."""

    PANIC_USER_KILL = "PANIC_USER_KILL"
    PANIC_SAFETY_SIGNAL = "PANIC_SAFETY_SIGNAL"

    RECOVERY_REPEAT_ERROR = "RECOVERY_REPEAT_ERROR"
    RECOVERY_STALL = "RECOVERY_STALL"
    RECOVERY_LOOP = "RECOVERY_LOOP"
    RECOVERY_REPLAN_LIMIT = "RECOVERY_REPLAN_LIMIT"

    HIGH_ASSURANCE_RISK_CLASS = "HIGH_ASSURANCE_RISK_CLASS"
    HIGH_ASSURANCE_RISK_SCORE = "HIGH_ASSURANCE_RISK_SCORE"
    HIGH_ASSURANCE_IRREVERSIBLE = "HIGH_ASSURANCE_IRREVERSIBLE"
    HIGH_ASSURANCE_LOW_GROUNDING = "HIGH_ASSURANCE_LOW_GROUNDING"
    HIGH_ASSURANCE_LOW_VERIFY_OUTCOME = "HIGH_ASSURANCE_LOW_VERIFY_OUTCOME"
    HIGH_ASSURANCE_CANDIDATE_DISAGREEMENT = "HIGH_ASSURANCE_CANDIDATE_DISAGREEMENT"

    CAUTIOUS_MEDIUM_RISK_CLASS = "CAUTIOUS_MEDIUM_RISK_CLASS"
    CAUTIOUS_LOW_INTENT_CONFIDENCE = "CAUTIOUS_LOW_INTENT_CONFIDENCE"
    CAUTIOUS_NEEDS_CLARIFICATION = "CAUTIOUS_NEEDS_CLARIFICATION"
    CAUTIOUS_HIGH_AMBIGUITY = "CAUTIOUS_HIGH_AMBIGUITY"
    CAUTIOUS_POLICY_DENIES = "CAUTIOUS_POLICY_DENIES"
    CAUTIOUS_TOOL_DEGRADED = "CAUTIOUS_TOOL_DEGRADED"
    CAUTIOUS_BUDGET_PRESSURE = "CAUTIOUS_BUDGET_PRESSURE"

    NORMAL_DEFAULT = "NORMAL_DEFAULT"

    FALLBACK_INVALID_METRICS = "FALLBACK_INVALID_METRICS"
    FALLBACK_EVALUATION_ERROR = "FALLBACK_EVALUATION_ERROR"
