from pathlib import Path

SESSION_DIRNAME = "session"
SESSIONS_DB_FILENAME = "sessions.db"
SESSION_DB_SUBPATH = Path(SESSION_DIRNAME) / SESSIONS_DB_FILENAME

STANDALONE_SESSION_DIRNAME = ".sessctl"
STANDALONE_SESSION_DB_SUBPATH = Path(STANDALONE_SESSION_DIRNAME) / SESSIONS_DB_FILENAME

IDENTITY_DIRNAME = "identity"
IDENTITY_DB_FILENAME = "identity.db"
IDENTITY_DB_SUBPATH = Path(IDENTITY_DIRNAME) / IDENTITY_DB_FILENAME

MEMORY_DIRNAME = "memory"
MEMORY_DB_FILENAME = "memory.db"
MEMORY_DB_SUBPATH = Path(MEMORY_DIRNAME) / MEMORY_DB_FILENAME

STANDALONE_CONTROLPLANE_DIRNAME = ".controlplane"
CONTROLPLANE_DIRNAME = "controlplane"

__all__ = (
    "CONTROLPLANE_DIRNAME",
    "IDENTITY_DB_FILENAME",
    "IDENTITY_DB_SUBPATH",
    "IDENTITY_DIRNAME",
    "MEMORY_DB_FILENAME",
    "MEMORY_DB_SUBPATH",
    "MEMORY_DIRNAME",
    "SESSIONS_DB_FILENAME",
    "SESSION_DB_SUBPATH",
    "SESSION_DIRNAME",
    "STANDALONE_CONTROLPLANE_DIRNAME",
    "STANDALONE_SESSION_DB_SUBPATH",
    "STANDALONE_SESSION_DIRNAME",
)
