from openminion.modules.tool import PLUGIN_CONTRACT_VERSION

GITHUB_PLUGIN_INTERFACE_VERSION = PLUGIN_CONTRACT_VERSION

GITHUB_TOKEN_ENV = "GITHUB_TOKEN"

GITHUB_API_BASE_URL_ENV = "GITHUB_API_BASE_URL"
DEFAULT_GITHUB_API_BASE_URL = "https://api.github.com"

GITHUB_TIMEOUT_SECONDS_ENV = "GITHUB_TIMEOUT_SECONDS"
DEFAULT_GITHUB_TIMEOUT_SECONDS = 30.0

DEFAULT_GITHUB_DIFF_MAX_LINES = 800

GITHUB_CHECK_RUNS_PER_PAGE = 100
GITHUB_CHECK_RUNS_MAX_PAGES = 3
GITHUB_CHECK_FAILURE_LIMIT = 10
GITHUB_CHECK_OUTPUT_MAX_CHARS = 2_000
GITHUB_WORKFLOW_RUNS_PER_PAGE = 50
GITHUB_WORKFLOW_RUNS_MAX_PAGES = 2

DEFAULT_GITHUB_PROVIDER_ID = "openminion-builtin-github"

DEFAULT_GITHUB_WRITE_ALLOWED_REPOSITORIES = ("openminion/test-repo-for-agent",)
DEFAULT_GITHUB_WRITE_ALLOWED_BRANCH_PREFIXES = ("openminion-smoke/",)
DEFAULT_GITHUB_WRITE_ALLOWED_PATH_PREFIXES = (".openminion-smoke/",)
DEFAULT_GITHUB_WRITE_ALLOWED_BASE_BRANCHES = ("main",)
DEFAULT_GITHUB_ALLOWED_WORKFLOWS: tuple[str, ...] = ()
DEFAULT_GITHUB_ALLOWED_WORKFLOW_REFS: tuple[str, ...] = ()
DEFAULT_GITHUB_ALLOWED_WORKFLOW_TARGETS: tuple[str, ...] = ()

GITHUB_POLICY_DENIED_REPO = "POLICY_DENIED_REPO"
GITHUB_POLICY_DENIED_DEFAULT_BRANCH = "POLICY_DENIED_DEFAULT_BRANCH"
GITHUB_POLICY_DENIED_BRANCH_PREFIX = "POLICY_DENIED_BRANCH_PREFIX"
GITHUB_POLICY_DENIED_PATH_PREFIX = "POLICY_DENIED_PATH_PREFIX"
GITHUB_POLICY_DENIED_FORCE_PUSH = "POLICY_DENIED_FORCE_PUSH"
GITHUB_POLICY_DENIED_MERGE = "POLICY_DENIED_MERGE"
GITHUB_POLICY_DENIED_DELETE = "POLICY_DENIED_DELETE"
GITHUB_POLICY_DENIED_BASE_BRANCH = "POLICY_DENIED_BASE_BRANCH"
GITHUB_POLICY_DENIED_PR_HEAD = "POLICY_DENIED_PR_HEAD"
GITHUB_POLICY_DENIED_WORKFLOW = "POLICY_DENIED_WORKFLOW"
GITHUB_POLICY_DENIED_WORKFLOW_REF = "POLICY_DENIED_WORKFLOW_REF"
GITHUB_POLICY_DENIED_WORKFLOW_INPUT = "POLICY_DENIED_WORKFLOW_INPUT"
GITHUB_POLICY_DENIED_WORKFLOW_TARGET = "POLICY_DENIED_WORKFLOW_TARGET"

__all__ = [
    "GITHUB_PLUGIN_INTERFACE_VERSION",
    "GITHUB_TOKEN_ENV",
    "GITHUB_API_BASE_URL_ENV",
    "DEFAULT_GITHUB_API_BASE_URL",
    "GITHUB_TIMEOUT_SECONDS_ENV",
    "DEFAULT_GITHUB_TIMEOUT_SECONDS",
    "DEFAULT_GITHUB_DIFF_MAX_LINES",
    "GITHUB_CHECK_RUNS_PER_PAGE",
    "GITHUB_CHECK_RUNS_MAX_PAGES",
    "GITHUB_CHECK_FAILURE_LIMIT",
    "GITHUB_CHECK_OUTPUT_MAX_CHARS",
    "GITHUB_WORKFLOW_RUNS_PER_PAGE",
    "GITHUB_WORKFLOW_RUNS_MAX_PAGES",
    "DEFAULT_GITHUB_PROVIDER_ID",
    "DEFAULT_GITHUB_WRITE_ALLOWED_REPOSITORIES",
    "DEFAULT_GITHUB_WRITE_ALLOWED_BRANCH_PREFIXES",
    "DEFAULT_GITHUB_WRITE_ALLOWED_PATH_PREFIXES",
    "DEFAULT_GITHUB_WRITE_ALLOWED_BASE_BRANCHES",
    "DEFAULT_GITHUB_ALLOWED_WORKFLOWS",
    "DEFAULT_GITHUB_ALLOWED_WORKFLOW_REFS",
    "DEFAULT_GITHUB_ALLOWED_WORKFLOW_TARGETS",
    "GITHUB_POLICY_DENIED_REPO",
    "GITHUB_POLICY_DENIED_DEFAULT_BRANCH",
    "GITHUB_POLICY_DENIED_BRANCH_PREFIX",
    "GITHUB_POLICY_DENIED_PATH_PREFIX",
    "GITHUB_POLICY_DENIED_FORCE_PUSH",
    "GITHUB_POLICY_DENIED_MERGE",
    "GITHUB_POLICY_DENIED_DELETE",
    "GITHUB_POLICY_DENIED_BASE_BRANCH",
    "GITHUB_POLICY_DENIED_PR_HEAD",
    "GITHUB_POLICY_DENIED_WORKFLOW",
    "GITHUB_POLICY_DENIED_WORKFLOW_REF",
    "GITHUB_POLICY_DENIED_WORKFLOW_INPUT",
    "GITHUB_POLICY_DENIED_WORKFLOW_TARGET",
]
